#! /bin/csh


#./fark_save.pl '?type=model&file=default.cfg3&password=&filterDir=%2Fopdata&filter=.*.nc&hits=%3F&index=&stack=%7Cfile1%7Cfile2&variables=%7Cdef~ HTTP/1.1" 200 285 "http://localhost/metfark/?type=model&file=default.cfg3'

#./fark_save.pl '?type=obs&file=default.cfg&password=&filterDir=%2Fmir%2Fbufr%2F&filter=.*.bufr&table=%2Fhome%2Fwww%2Ffark-perl_0.15%2Fbufrtables%2F&bufrType=4&subType=145&typeInfo=acar&indexTarget=timeObs&indexExp=sec1970(yy%2Cmm%2Cdd%2Chh)&obsTargets=%7Cyy~10~4001~YEAR~~%7Cmm~11~4002~MONTH~~%7Cdd~12~4003~DAY~~%7Chh~13~4004~HOUR~~%7Cmi~14~4005~MINUTE~~'
./fark_save.pl '?type=obs&file=a%2Ftest.cfg&password=&filterDir=%2Fmir%2Fbufr%2F&filter=.*.bufr&table=%2Fhome%2Fwww%2Ffark-perl_0.15%2Fbufrtables%2F&bufrType=4&subType=145&typeInfo=acar&indexTarget=timeObs&indexExp=sec1970(yy%2Cmm%2Cdd%2Chh)&obsTargets=%7Cyy~10~4001~YEAR~~%7Cmm~11~4002~MONTH~~%7Cdd~12~4003~DAY~~%7Chh~13~4004~HOUR~~%7Cmi~14~4005~MINUTE~~ HTTP/1.1" 200 366 "http://pc4804.pc.met.no/metfark/?type=obs&file=a/test.cfg'
