#! /bin/csh
#./fark_load.pl '&type=model;arg[]=abc'
#./fark_load.pl '&type=obs;arg[]=default.cfg'
#./fark_load.pl '?type%5B%5D=plot&type%5B%5D=cat&arg%5B%5D='
#
#./fark_load.pl '&type=obs;arg[]=abc'
./fark_load.pl '&type=coloc&arg%5B%5D=undefined'
#./fark_load.pl '&type=coloc'
#
