#! /bin/csh
#./fark_find.pl '?type=obsfile&file=default.cfg&password=&target=/home/www/bufr/conv00.bufr'
#./fark_find.pl '?type=obs&file=hirlam12+conv+bufr&password=&filterDir=%2Fhome%2Fwww%2Fbufr&filter=.*bufr&table=%2Fhome%2Fwww%2Ffark-perl_0.15%2Fbufrtables%2F'
#./fark_find.pl '?type=modelfile&file=default.cfg&password=&index=time&target=%2Fhome%2Fwww%2Fnetcdf%2Ffark-perl_0.14%2Flibmod%2Fncll%2Fsimsd00X.nc'
#./fark_find.pl '?type=model&file=default.cfg&password=&filterDir=%2Fhome%2Fwww%2Fnetcdf&filter=.*nc'
#
#./fark_find.pl '?type=modelfile&file=default.cfg&password=&target=%2Fmir%2Fnetcdf%2FAROME_MetCoOp_00_sfx.nc'
#./fark_find.pl '?type=modelfile&file=default.cfg&password=&target=%2Fmir%2Fnetcdf%2FAROME_MetCoOp_00_sfx.nc'
#
#./fark_find.pl 'type=obsfile&file=default.cfg&target=%2Fhome%2Fubuntu%2Fbufr%2Fconv18.bufr_20160201&password=&filterDir=%2Fmir%2Fbufr%2F&filter=conv.*.bufr&table=%2Fhome%2Fwww%2Ffark-perl_0.15%2Fbufrtables%2F&obsTargets=&indexTarget=&indexExp=&bufrType=0&subType=1&typeInfo=synop+land'
#
#./fark_find.pl 'type=obsfile&file=default.cfg&target=%2Fhome%2Fubuntu%2Fbufr%2Fconv00.bufr_20160201&password=&filterDir=%2Fhome%2Fubuntu%2Fbufr%2F&filter=.*%5C.bufr&table=%2Fhome%2Fubuntu%2Ffark-perl_0.15%2Fbufrtables%2F&obsTargets=%7Cyy~10~4001~YEAR~~%7Cmm~11~4002~MONTH~~%7Cdd~12~4003~DAY~~%7Chh~13~4004~HOUR~~%7Cmi~14~4005~MINUTE~~&indexTarget=timeObs&indexExp=sec1970(yy%2Cmm%2Cdd%2Chh%2Cmi)&bufrType=2&subType=101&typeInfo=temp'
#

#./fark_find.pl 'type=obsfile&file=default.cfg&target=%2Fmir%2Fbufr%2Fconv00.bufr&password=&filterDir=%2Fmir%2Fbufr%2F&filter=conv.*.bufr&table=%2Fhome%2Fwww%2Ffark-perl_0.15%2Fbufrtables%2F&obsTargets=%7Cyy~4~4001~YEAR~~%7Cmm~5~4002~MONTH~~%7Cdd~6~4003~DAY~~%7Chh~7~4004~HOUR~~%7Cmi~8~4005~MINUTE~~&indexTarget=timeObs&indexExp=+sec1970(yy%2Cmm%2Cdd%2Chh%2Cmi)*1000&bufrType=0&subType=1&typeInfo=synop+land'

./fark_find.pl 'type=obsfile&file=default.cfg&target=%2Fhome%2Fubuntu%2Fbufr%2Fconv18.bufr_20160201&password=&filterDir=%2Fhome%2Fubuntu%2Fbufr%2F&filter=.*%5C.bufr&table=%2Fhome%2Fubuntu%2Ffark-perl_0.15%2Fbufrtables%2F&obsTargets=%7Cyy~5~4001~YEAR~~%7Cmm~6~4002~MONTH~~%7Cdd~7~4003~DAY~~%7Chh~8~4004~HOUR~~%7Cmi~9~4005~MINUTE~~&indexTarget=timeObs&indexExp=sec1970(yy%2Cmm%2Cdd%2Chh%2Cmi)&bufrType=2&subType=101&typeInfo=temp'
