#!/usr/bin/env Rscript
#
# Column=x-value
# Column=y-value
#
# Attribute=title|your title
# Attribute=x-label|x-label
# Attribute=y-label|y-label
# Attribute=Orientation|landscape:portrait
# Attribute=Format|Jpeg:png:PDF:Postscript
# Attribute=Version|1.0:
#
# Id=1|circle
# Id=2|star
# Id=3|triangle
# Id=4|blue-circle
# Id=5|red-circle
# Id=6|gold-circle
# Id=7|blue-triangle
# Id=8|red-triangle
# Id=9|gold-triangle
#
# Usage: Rscript --vanilla skill table.txt plot.ps
#

## check arguments
args = commandArgs(trailingOnly=TRUE)
if (length(args)==0) {
  stop("At least one argument must be supplied (input file).n", call.=FALSE)
} else if (length(args)==1) {
  # default output file
  args[2] = "out.ps"
}

## read table input file...
processFile = function(args[1]) {
  con = file(filepath, "r");
  while ( TRUE ) {
    line = readLines(con, n = 1);
    if ( length(line) == 0 ) {
      break;
    }
    items <- strsplit(line, " ")
    print(line);
    print(items);
  }
  close(con)
}

## make graphical output
# jpeg('args[2]');
# x=c(0,1);
# y=c(2,10);
# plot(x,y);
# dev.off();
