#!/usr/bin/env Rscript
#
# Column=x-expression
# Column=y-expression
#
# Attribute=title|your title
# Attribute=x-label|x-label
# Attribute=y-label|y-label
# Attribute=Orientation|landscape:portrait
# Attribute=Format|PostScript:png:Jpeg
# Attribute=Version|1.0:
#
# Id=1|circle
# Id=2|star
# Id=3|triangle
# Id=4|blue-circle
# Id=5|red-circle
# Id=6|gold-circle
# Id=7|blue-triangle
# Id=8|red-triangle
# Id=9|gold-triangle
#
# Usage: Rscript --vanilla skill table.txt plot.ps
args = commandArgs(trailingOnly=TRUE)
#

if (length(args)==0) {
  stop("At least one argument must be supplied (input file).n", call.=FALSE)
} else if (length(args)==1) {
  # default output file
  args[2] = "out.ps"
}

## program...
df = read.table(args[1], header=TRUE)
##
## ... do stuff here...
