#!/usr/bin/env Rscript
#
# Id=1|circle/solid
# Id=2|triangle/dashed
# Id=3|pluss/dotted
# Id=4|cross/dot dashed
# Id=5|diamond/long dashed
# Id=6|down triangle/two dashed
# Id=7|cross square/solid
# Id=8|star/dashed
# Id=9|cross diamond/dotted
#
# Attribute=_N|1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
# Attribute=_P|0:1:2:3:4:5
# Attribute=title_string_N|Title
# Attribute=min_N|-999999
# Attribute=max_N|+999999
# Attribute=axis_string_N|Label
# Attribute=file_string_N|var
# Attribute=axis_pred_P|Predictor axis label
# Attribute=file_pred_P|Predictor file label
# Attribute=Orientation|landscape:portrait
# Attribute=Format|Jpeg:png:PDF:PostScript
# Attribute=Suffix|.jpg:.png:.pdf:.ps
# Attribute=Version|1.0:
#
# Column=cycle_epoch
# Column=time_epoch
# Column=obs_file_id
# Column=msg_id
# Column=loc_id
# Column=area
# Column=lat_deg
# Column=lon_deg
# Column=altitude_meter
# Column=model_variable_N
# Column=obs_variable_N
# Column=pred_P
#
# Usage: Rscript --vanilla verify table.txt plot
#
library(farkRPackage);

print (paste("################### starting script #####################"));

args <- getArguments(); 

tablefile = args[1];
prefix = args[2];

logfile=paste0(tablefile,".Rout");

print (paste("Logfile=",logfile));

#sink(logfile);

leg  <- readComments(tablefile,"LEGENDS");
attr <- readComments(tablefile,"ATTRIBUTES");
cols <- readComments(tablefile,"COLUMNS");

print (paste("Reading data from ",tablefile));

raw <- readData(tablefile); 

#raw <- raw[1:1000,];

attr

suffix = attr["Suffix",];

setcol  = "set";
refcol  = "cycle_epoch";
timecol = "time_epoch";
areacol = "area";
altcol  = "altitude_meter";

data <- overlap(raw,setcol,c("cycle_epoch","obs_file_id","msg_id","loc_id"));
areal = "lowland";
areah = "highland";

areaq = unique(data[[1]][,areacol]);

rm(raw);gc(); # free memory

print (paste("Splitting data"));

#thres = attr["geopotential_threshold",];
thres = 20; # ~20 meter threshold for high/low stations

p <- 0; # default is zero predictors

if ("_P" %in% rownames(attr)) { p = attr["_P",];}

print(paste("Predictors:",p));

for (aa in areaq) { # loop over areas

    print(paste("Processing area:",aa));
    
    nn <- equals(data[[1]],areacol,aa);
    nl <- below(data[[1]],altcol,thres,nn);
    nh <- above(data[[1]],altcol,thres,nn);
    
    for (ii in 1:attr["_N",]) {
        
        file=attr[paste0("file_string",ii),];
        title=attr[paste0("title_string",ii),];
        min=as.numeric(attr[paste0("min",ii),]);
        max=as.numeric(attr[paste0("max",ii),]);
        label=attr[paste0("axis_string",ii),];
        obscol=paste0("obs_variable",ii);
        modcol=paste0("model_variable",ii);
        
        obslabel=paste("observed",label);
        modlabel=paste("modelled",label);
        
        if (p>0) {
            for (jj in 1:p) {
                predstr=attr[paste0("file_pred",jj),];
                predlab=attr[paste0("axis_pred",jj),];
                predcol=paste0("pred",jj);
                preddir="ascending";
                predfile=paste0(prefix,file,"_",predstr,"_hl","_",aa,suffix);
                print(paste0("Processing (highland) '",predfile,"'"));
                predictorPlot(predfile,attr,leg,data,title,setcol,refcol,timecol,
                              predlab,predcol,preddir,obscol,modcol,label,min,max,
                              areah,nh);
                predfile=paste0(prefix,file,"_",predstr,"_ll","_",aa,suffix);
                print(paste0("Processing (lowland) '",predfile,"'"));
                predictorPlot(predfile,attr,leg,data,title,setcol,refcol,timecol,
                              predlab,predcol,preddir,obscol,modcol,label,min,max,
                              areal,nl);
            }
        }
        ;# score plot highland
        scorefile=paste0(prefix,file,"_score_hl","_",aa,suffix);
        print(paste0("Processing (highland) '",scorefile,"'"));
        scorePlot(scorefile,attr,leg,data,title,setcol,refcol,timecol,
                  altcol,obscol,modcol,label,min,max,
                  areah,nh);
        
        ;# score plot lowland
        scorefile=paste0(prefix,file,"_score_ll","_",aa,suffix);
        print(paste0("Processing (lowland) '",scorefile,"'"));
        scorePlot(scorefile,attr,leg,data,title,setcol,refcol,timecol,
                  altcol,obscol,modcol,label,min,max,
                  areal,nl);
        
        ;# series plot
        seriesfile=paste0(prefix,file,"_series_hl","_",aa,suffix);
        print(paste0("Processing (highland) '",seriesfile,"'"));
        seriesPlot(seriesfile,attr,leg,data,title,setcol,refcol,timecol,
                   altcol,obscol,modcol,label,min,max,
                   areah,nh);
        
        ;# series plot
        seriesfile=paste0(prefix,file,"_series_ll","_",aa,suffix);
        print(paste0("Processing (lowland) '",seriesfile,"'"));
        seriesPlot(seriesfile,attr,leg,data,title,setcol,refcol,timecol,
                   altcol,obscol,modcol,label,min,max,
                   areal,nl);
        
        ;# time plot
        timefile=paste0(prefix,file,"_time_hl","_",aa,suffix);
        print(paste0("Processing (highland) '",timefile,"'"));
        timePlot(timefile,attr,leg,data,title,setcol,refcol,timecol,
                 altcol,obscol,modcol,label,min,max,
                 areah,nh);
        
        ;# time plot
        timefile=paste0(prefix,file,"_time_ll","_",aa,suffix);
        print(paste0("Processing (lowland) '",timefile,"'"));
        timePlot(timefile,attr,leg,data,title,setcol,refcol,timecol,
                 altcol,obscol,modcol,label,min,max,
                 areal,nl);
        
        ;# scatter plot
        scattfile=paste0(prefix,file,"_scatter_hl","_",aa,suffix);
        print(paste0("Processing (highland) '",scattfile,"'"));
        scatterPlot(scattfile,attr,leg,data,title,setcol,refcol,timecol,
                    altcol,obscol,modcol,obslabel,modlabel,min,max,
                    areah,nh);
        
        ;# scatter plot
        scattfile=paste0(prefix,file,"_scatter_ll","_",aa,suffix);
        print(paste0("Processing (lowland) '",scattfile,"'"));
        scatterPlot(scattfile,attr,leg,data,title,setcol,refcol,timecol,
                    altcol,obscol,modcol,obslabel,modlabel,min,max,
                    areal,nl);
        
        ;# histogram plot
        histfile=paste0(prefix,file,"_hist_hl","_",aa,suffix);
        print(paste0("Processing (highland) '",histfile,"'"));
        histPlot(histfile,attr,leg,data,title,setcol,refcol,timecol,
                 altcol,obscol,modcol,label,min,max,
                 areah,nh);
        
        ;# histogram plot
        histfile=paste0(prefix,file,"_hist_ll","_",aa,suffix);
        print(paste0("Processing (lowland) '",histfile,"'"));
        histPlot(histfile,attr,leg,data,title,setcol,refcol,timecol,
                 altcol,obscol,modcol,label,min,max,
                 areal,nl);
        
        ;# profile plot
        proffile=paste0(prefix,file,"_prof","_",aa,suffix);
        print(paste0("Processing '",proffile,"'"));
        profilePlot(proffile,attr,leg,data,title,setcol,refcol,timecol,
                    "altitude (m)",altcol,"ascending",obscol,modcol,label,min,max,
                    areah,nh,areal,nl);
    }
}
                           #warnings();
