#!/usr/bin/env Rscript
#
# Id=1|circle/solid
# Id=2|triangle/dashed
# Id=3|pluss/dotted
# Id=4|cross/dot dashed
# Id=5|diamond/long dashed
# Id=6|down triangle/two dashed
# Id=7|cross square/solid
# Id=8|star/dashed
# Id=9|cross diamond/dotted
#
# Attribute=_n|1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
# Attribute=title_string_n|Title
# Attribute=axis_string_n|Label
# Attribute=file_string_n|var
# Attribute=Orientation|landscape:portrait
# Attribute=Format|Jpeg:png:PDF:PostScript
# Attribute=Suffix|.jpg:.png:.pdf:.ps
# Attribute=Version|1.0:
#
# Column=cycle_epoch
# Column=time_epoch
# Column=obs_id
# Column=lat_deg
# Column=lon_deg
# Column=altitude_meter
# Column=model_variable_n
# Column=obs_variable_n
#
# Usage: Rscript --vanilla verify table.txt plot
#
library(farkRPackage);

print (paste("################### starting script #####################"));

args <- getArguments(); 
tablefile = args[1];
prefix = args[2];

leg <- readComments(tablefile,"LEGENDS");
attr <- readComments(tablefile,"ATTRIBUTES");
cols <- readComments(tablefile,"COLUMNS");
data <- readData(tablefile);

suffix = attr["Suffix",];

setcol  = "set";
refcol  = "cycle_epoch";
timecol = "time_epoch";
idcol   = "obs_id";
altcol  = "altitude_meter";

print (data[1,]);

#thres = attr["geopotential_threshold",];
thres = 20; # ~20 meter threshold for high/low stations 
n <- norwegian(data,idcol);
nl <- below(data,altcol,thres,n);
nh <- above(data,altcol,thres,n);

for (ii in 1:attr["_n",]) {

    file=attr[paste0("file_string",ii),];
    title=attr[paste0("title_string",ii),];
    label=attr[paste0("axis_string",ii),];
    obscol=paste0("obs_variable",ii);
    modcol=paste0("model_variable",ii);
    obslabel=paste("observed",label);
    modlabel=paste("modelled",label);
    
    ;# score plot
    scorefile=paste0(prefix,file,"_score",suffix);
    print(paste0("Processing '",scorefile,"'"));
    scorePlot(scorefile,attr,leg,data,title,setcol,refcol,
              timecol,idcol,altcol,modcol,obscol,label,
              "Norwegian highland",nh,"Norwegian lowland",nl);
    
    ;# series plot
    seriesfile=paste0(prefix,file,"_series",suffix);
    print(paste0("Processing '",seriesfile,"'"));
    seriesPlot(seriesfile,attr,leg,data,title,setcol,refcol,timecol,idcol,
               altcol,modcol,obscol,label,
              "Norwegian highland",nh,"Norwegian lowland",nl);

    ;# scatter plot
    scattfile=paste0(prefix,file,"_scatter",suffix);
    print(paste0("Processing '",scattfile,"'"));
    scatterPlot(scattfile,attr,leg,data,title,setcol,refcol,timecol,idcol,
                altcol,obscol,modcol,obslabel,modlabel,
                "Norwegian highland",nh,"Norwegian lowland",nl);

    ;# histogram plot
    histfile=paste0(prefix,file,"_hist",suffix);
    print(paste0("Processing '",histfile,"'"));
    histPlot(histfile,attr,leg,data,title,setcol,refcol,timecol,idcol,
             altcol,modcol,obscol,label,
             "Norwegian highland",nh,"Norwegian lowland",nl);

    ;# profile plot
    proffile=paste0(prefix,file,"_prof",suffix);
    print(paste0("Processing '",proffile,"'"));
    profilePlot(proffile,attr,leg,data,title,setcol,refcol,timecol,idcol,
             "altitude (m)",altcol,"ascending",modcol,obscol,label,
             "Norwegian highland",nh,"Norwegian lowland",nl);
}

#warnings();

