#!/usr/bin/env Rscript
#
# Id=1|circle/solid
# Id=2|triangle/dashed
# Id=3|pluss/dotted
# Id=4|cross/dot dashed
# Id=5|diamond/long dashed
# Id=6|down triangle/two dashed
# Id=7|cross square/solid
# Id=8|star/dashed
# Id=9|cross diamond/dotted
#
# Attribute=_n|1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
# Attribute=title_string_n|Title
# Attribute=min_n|-999999
# Attribute=max_n|+999999
# Attribute=axis_string_n|Label
# Attribute=file_string_n|var
# Attribute=Orientation|landscape:portrait
# Attribute=Format|Jpeg:png:PDF:PostScript
# Attribute=Suffix|.jpg:.png:.pdf:.ps
# Attribute=Version|1.0:
#
# Column=cycle_epoch
# Column=time_epoch
# Column=obs_id
# Column=area
# Column=lat_deg
# Column=lon_deg
# Column=pressure_hpa
# Column=altitude_meter
# Column=model_variable_n
# Column=obs_variable_n
#
# Usage: Rscript --vanilla verify table.txt plot
#
library(farkRPackage);

print (paste("################### starting script #####################"));

args <- getArguments(); 
tablefile = args[1];
prefix = args[2];

leg <- readComments(tablefile,"LEGENDS");
attr <- readComments(tablefile,"ATTRIBUTES");
cols <- readComments(tablefile,"COLUMNS");
data <- readData(tablefile);

suffix = attr["Suffix",];

setcol  = "set";
refcol  = "cycle_epoch";
timecol = "time_epoch";
idcol   = "obs_id";
areacol = "area";
altcol  = "altitude_meter";
pcol   = "pressure_hpa";


#thres = attr["geopotential_threshold",];
n <- norwegian(data,idcol);

#if (sum(n) < 1) { stop ("No norwegian stations found.");};

for (ii in 1:attr["_n",]) {

    file=attr[paste0("file_string",ii),];
    title=attr[paste0("title_string",ii),];
    label=attr[paste0("axis_string",ii),];
    obscol=paste0("obs_variable",ii);
    modcol=paste0("model_variable",ii);
    obslabel=paste("observed",label);
    modlabel=paste("modelled",label);

    ;# profile plot
    proffile=paste0(prefix,file,"_prof",suffix);
    print(paste0("Processing '",proffile,"'"));
    profilePlot(proffile,attr,leg,data,title,setcol,refcol,timecol,idcol,
                "Pressure (hPA)",pcol,"descending",modcol,obscol,label);
                                        #,"Norwegian stations",n);
}

#warnings();

