#!/usr/bin/env Rscript
#
# Id=1|circle
# Id=2|star
# Id=3|triangle
#
# Attribute=_n|1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
# Attribute=title_n|Title
# Attribute=label_n|Label
# Attribute=name_n|var
# Attribute=Orientation|landscape:portrait
# Attribute=Format|Jpeg:png:PDF:PostScript
# Attribute=Suffix|.jpg:.png:.pdf:.ps
# Attribute=Version|1.0:
#
# Column=cycle_epoch
# Column=epoch
# Column=lat
# Column=lon
# Column=model_variable_n
# Column=obs_id
# Column=obs_variable_n
#
# Usage: Rscript --vanilla verify table.txt plot
#

library(farkRPackage);

args <- getArguments(); 
tablefile <- args[0];
prefix <- args[1];
suffix = attr$Suffix;

legs <- readComments(tablefile,"LEGENDS");
attr <- readComments(tablefile,"ATTRIBUTES");
cols <- readComments(tablefile,"COLUMNS");
data <- readData(tablefile);

# mountain data
mnt_id <- c("22522","2981","2741","2773");
mnt_name = "Mountain stations";
mnt_data <- data[data%obs_id %in% mnt_id,];

# coastal data
coast_id <- c("2758","2794","2949","2983");
coast_name = "Coastal stations";
coast_data <- data[data%obs_id %in% coast_id,];

# thinned data
set.seed(1);
thin_n = min(c(1000,nrow(data)));
thin_name = "Thinned data";
thin_data <- sample(data,thin_n, replace=TRUE)

for (ii in 1:attr$_n) {

 name=attr[,get(paste0("name",ii)];
 title=attr[,get(paste0("title",ii)];
 label=attr[,get(paste0("label",ii)];
 refcol="cycle_epoch";
 timecol="epoch";
 obscol=paste0("obs_value",ii);
 modcol=paste0("model_value",ii);
 obslabel=paste("observation",label);
 modlabel=paste("model",label);

 scattfile=paste0(prefix,name,"_scatter",suffix);
 print(paste0("Processing '",scattfile,"'"));
 scatterPlot(scattfile,attr,legs,thin_data,title,setcol,obscol,modcol,obslabel,modlabel);

 seriesfile=paste0(prefix,name,"_series",suffix);
 print(paste0("Processing '",seriesfile,"'"));
 seriesPlot(seriesfile,attr,legs,data,title,setcol,timecol,modcol,obscol,label);

 scorefile=paste0(prefix,name,"_score",suffix);
 print(paste0("Processing '",scorefile,"'"));
 scorePlot(seriesfile,attr,legs,data,title,setcol,refcol,timecol,modcol,obscol,label);

 histfile=paste0(prefix,name,"_hist",suffix);
 print(paste0("Processing '",histfile,"'"));
 histPlot(histfile,attr,legs,data,title,setcol,refcol,timecol,modcol,obscol,label);

}

