#! gmake
#
# NOTE: make sure you are using GNU's "make-3.75.tar.gz" or older...
#
#
# A list of the files or directories that should be 'made'

 ONLY = build

# A list of files to be compiled in given order
# ORDER =
#
# A list of the files or directories that should not be 'made'
# STATIC = 
#
#.IGNORE:
#
include MakeInclude
#
