#! /bin/csh
./fark_find.pl '?type=obs&file=starc%2Ftemp_test.cfg&password=&filterDir=%2Flustre%2FstoreB%2Fimmutable%2Farchive%2Fprojects%2Fmetproduction%2FDNMI_OBS_BUFR%2F2018%2F02%2F14&filterDirMin=&filterDirMax=30&filterFile=temp_2018021400.bufr&table=%2Fmetfark%2Fbufrtables%2F&obsTargets=%7Cyy~5~4001~YEAR~undefined~undefined%7Cmm~6~4002~MONTH~undefined~undefined%7Cdd~7~4003~DAY~undefined~undefined%7Chh~8~4004~HOUR~undefined~undefined%7Cmi~9~4005~MINUTE~undefined~undefined&indexTarget=obs_time&indexExp=sec1970(yy%2Cmm%2Cdd%2Chh%2Cmi)&bufrType=2&subType=101&typeInfo=temp'


#'?type=obsfile&file=starc%2Fsyno20180102.cfg&target=%2Flustre%2FstoreB%2Fimmutable%2Farchive%2Fprojects%2Fmetproduction%2FDNMI_OBS_BUFR%2F2018%2F01%2F02%2Fsyno_2018010206.bufr&password=&filterDir=%2Flustre%2FstoreB%2Fimmutable%2Farchive%2Fprojects%2Fmetproduction%2FDNMI_OBS_BUFR%2F2018%2F01%2F02&filterFile=syno_2018010206.bufr&table=%2Fmetfark%2Fbufrtables%2F&obsTargets=%7Cyy~5~4001~YEAR%7Cmm~6~4002~MONTH%7Cdd~7~4003~DAY%7Chh~8~4004~HOUR%7Cmi~9~4005~MINUTE&indexTarget=time&indexExp=sec1970(yy%2Cmm%2Cdd%2Chh%2Cmi)&bufrType=0&subType=1&typeInfo=synop+land'



#'?type=model&file=meps%2Fmember0.cfg&password=fark&filterDir=%2Flustre%2FstoreB%2Fimmutable%2Farchive%2Fprojects%2Fmetproduction%2Fmeps&filterDirMin=&filterDirMax=1&filterFile=meps_mbr0_extracted_2_5km_%5Cd%5Cd%5Cd%5Cd%5Cd%5Cd%5Cd%5CdT%5Cd%5CdZ.nc&indexTarget=time_trg&indexVariable=time'

