#! /bin/csh
##

##&debug=1


./fark_find.pl '?type=joinfile&file=default.cfg&password=fark&target=%2Flustre%2FstoreA%2Fproject%2Fnwp%2Ffark%2F2019%2F10%2F22%2Fmeps_syno_003d_R.table&debug=1'



#####?type=joinfile&password=fark&file=default.cfg&password=&target=%2Flustre%2FstoreA%2Fproject%2Fnwp%2Ffark%2F2019%2F10%2F21%2Fmeps_syno_003d_R.table'

#
#./fark_find.pl '?type=modelfile&file=default.cfg&password=&target=%2Flustre%2FstoreB%2Fimmutable%2Farchive%2Fprojects%2Fmetproduction%2Fmeps%2F2019%2F10%2F27%2Fmeps_mbr0_extracted_2_5km_20191027T12Z.nc'
