#! /bin/csh

./fark_load.pl '?type%5B%5D=plot&type%5B%5D=cat&arg%5B%5D=default.cfg'


#./fark_load.pl '?type=auto&root=auto.cfg'
#./fark_load.pl '?type=coloc&arg%5B%5D=default.cfg'
#  type=coloc&arg%5B%5D=starc%2FaromeSyno20170101.cfg'
# ?type=obs&arg%5B%5D=starc%2Fsyno20170101.cfg'
# ?type=obs&arg%5B%5D=default.cfg'
#./fark_load.pl '?type=&arg%5B%5D='
# ./fark_load.pl '&type=obs;arg[]=default.cfg'
# ./fark_load.pl '?type=coloc&arg%5B%5D=3'
# ./fark_load.pl '?type=plot&arg%5B%5D=starc%2FaromeSyno.cfg'
#
# ./fark_load.pl '&type=obs;arg[]=abc'
# ./fark_load.pl '&type=coloc&arg%5B%5D=undefined'
# ./fark_load.pl '&type=coloc'
#
