/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.28 from the
 * contents of fark.xs. Do not edit this file, edit fark.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "fark.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

void mod_opensession_(int* mid, char* crc250, int* irc, int len1);
void mod_clearfilestack_(int* mid,char* varname, char* crc250,int* irc, int len1, int len2);
void mod_cleartargetstack_(int* mid,char* crc250,int* irc, int len1);
void mod_closesession_(int* mid, char*crc250, int* irc, int len1);
void mod_setindex_(int* mid, char* trgname, char* varname, char* crc250, int* irc, int len1, int len2, int len3);
void mod_setindexlimits_(int* mid, char* smin, char* smax, char* crc250, int* irc, int len1, int len2, int len3);
void mod_determinefileorder_(int* mid, char* crc250, int* irc, int len1);
void mod_loadcache_(int* mid,char* path,char* crc250,int* irc, int len1,int len2);
void mod_makecache_(int* mid,char* path,char* crc250,int* irc, int len1,int len2);
void mod_peekfile_(int* mid,int* maxrep,int* nrep,char* rep250,char* crc250,int* irc, int len1,int len2);
void mod_peekfilelen_(int* mid,int* maxrep,char* crc250,int* irc, int len1);
void mod_popfile_(int* mid,char* path250,char* crc250,int* irc, int len1,int len2);
void mod_pushfile_(int* mid,char* path,char* crc250,int* irc, int len1,int len2);
void mod_pushtarget_(int* mid,char* trg,char* var,char* min,char* max, char* crc250,int* irc, int len1,int len2,int len3,int len4,int len5);
void mod_setfilter_ (int* cid, char* flt,  char* crc250, int* irc, int len1, int len2);

void obs_opensession_(int* oid,char* crc250,int* irc, int len1);
void obs_clearfilestack_(int* oid,char* crc250,int* irc, int len1);
void obs_cleartargetstack_(int* oid,char* crc250,int* irc, int len1);
void obs_closesession_(int* oid,char* crc250,int* irc, int len1);
void obs_loadcache_(int* oid,char* path,char* crc250,int* irc, int len1,int len2);
void obs_makecache_(int* oid,char* path,char* crc250,int* irc, int len1,int len2);
void obs_peekfile_(int* oid,int* maxrep,int* nrep,char* rep250,char* crc250,int* irc,int len1,int len2);
void obs_peekfilelen_(int* oid,int* maxrep,char* crc250,int* irc, int len1);
void obs_popfile_(int* oid,char* path250,char* crc250,int* irc, int len1,int len2);
void obs_pushfile_(int* oid,char* path,char* crc250,int* irc, int len1,int len2);
void obs_pushtarget_(int* oid,char* trg,char* pos,char* descr,char* info,char* min,char* max, char* crc250,int* irc, int len1,int len2,int len3,int len4,int len5,int len6,int len7);
void obs_settablepath_(int* oid,char* path250,char* crc250,int* irc, int len1,int len2);
void obs_setindex_(int* oid,char* trg80,char* exp250, char* crc250,int* irc, int len1,int len2,int len3);
void obs_setindexlimits_(int* oid,char* s25,char* e25,char* crc250,int* irc, int len1,int len2,int len3);
void obs_setbufrtype_(int* oid,int* bufrType, int* subType, char* crc250,int* irc, int len1);
void obs_setfilter_ (int* cid, char* flt,  char* crc250, int* irc, int len1, int len2);

void col_opensession_(int* cid, char* crc250, int* irc, int len1);
void col_closesession_(int* cid, char* crc250, int* irc, int len1);
void col_expression_(char* exp250, char* crc250, int* irc, int len1, int len2);
void col_setmodcache_(int* cid, char* path250, char* crc250, int* irc, int len1, int len2);
void col_setobscache_(int* cid, char* path250, char* crc250, int* irc, int len1, int len2);
void col_pushdefault_(int* cid,char* crc250,int* irc, int len1);
void col_cleardefaultstack_(int* cid,char* crc250,int* irc, int len1);
void col_adddefault_(int* cid,char* trg,char* val, char* crc250,int* irc, int len1,int len2,int len3);
void col_pushmatch_(int* cid, char* modName, char* obsExpr, char* smin, char* smax, char* crc250, int* irc, int len1, int len2, int len3, int len4, int len5);
void col_makematchlist_(int* cid, int* mid, char* crc250, int* irc, int len1);
void col_clearmatchstack_(int* mid, char* crc250, int* irc, int len1, int len2);
void col_makexml_(int* cid, int* mid, int* oid, char* xml250, int* test,char* fill250, char*  crc250, int* irc, int len1, int len2, int len3);
void col_setxmlfile_(int* pid, char* fn250, char* crc250, int* irc, int len1, int len2);
void col_getxmlfile_(int* pid, char* fn250, char* crc250, int* irc, int len1, int len2);

void par_setshapefile_(char* fn250, char* cname11, char* crc250, int* irc, int len1, int len2, int len3);
void par_simplifyshapes_(char* tol20, char* crc250, int* irc, int len1, int len2);
void par_clearshapefile_(char* crc250, int* irc, int len1);
void par_setvariable_ (char* variable,  char* crc250, int* irc, int len1, int len2);
void par_setvalue_ (int* value,  char* crc250, int* irc, int len1);
void par_setoffset_ (char* offset,  char* crc250, int* irc, int len1, int len2);
void par_getoffset_ (char* off25,  char* crc250, int* irc, int len1, int len2);

void tab_opensession_(int* pid, char* crc250, int* irc, int len1);
void tab_closesession_(int* pid, char* crc250, int* irc, int len1);
void tab_clearfilestack_(int* mid,char* crc250,int* irc, int len1);
void tab_pushfile_(int* mid,char* path,char* crc250,int* irc, int len1,int len2);
void tab_maketablefile_(int* pid, int* cid, int* mid, int* oid, char* tab250, char* gra250,char* cat250,int* test,char* fill250,char*  crc250, int* irc, int len1, int len2, int len3, int len4, int len5);
void tab_jointablefile_(int* pid, int* cid, int* mid, int* oid, char* tab250, char* gra250,char* cat250,int* test,char* fill250,char*  crc250, int* irc, int len1, int len2, int len3, int len4, int len5);
void tab_settype_(int* pid, char* type250, char* crc250, int* irc, int len1, int len2);
void tab_clearattrstack_(int* pid, char* crc250, int* irc, int len1, int len2);
void tab_pushattr_(int* pid, char* name80, char* value250, char* crc250, int* irc, int len1, int len2, int len3);
void tab_limitcolumn_(int* pid, char* name, char* min, char* max, char* crc250, int* irc, int len1, int len2, int len3, int len4);
void tab_clearsetstack_(int* pid, char* crc250, int* irc, int len1, int len2);
void tab_clearcolumn_(int* pid, char* crc250, int* irc, int len1);
void tab_pushcolumn_(int* pid, char* name80, char* exp250, char* crc250, int* irc, int len1, int len2, int len3);
void tab_pushset_(int* pid, int* cid, int* mid, int* oid, char* name250, char* legend250, char* crc250, int* irc, int len1, int len2, int len3);
void tab_settablefile_(int* pid, char* fn250, char* crc250, int* irc, int len1, int len2);
void tab_gettablefile_(int* pid, char* fn250, char* crc250, int* irc, int len1, int len2);
void tab_setgraphicsdir_(int* pid, char* fn250, char* crc250, int* irc, int len1, int len2);
void tab_getgraphicsdir_(int* pid, char* fn250, char* crc250, int* irc, int len1, int len2);
void tab_streptablefile_(int* pid, char* crc250, int* irc, int len1);
void tab_strepgraphicsdir_(int* pid, char* crc250, int* irc, int len1);
void tab_setdebug_(int* ideb);

#line 95 "fark.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 239 "fark.c"

XS_EUPXS(XS_fark_xs_openModelSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_openModelSession)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 101 "fark.xs"
      int  mid;
      int  irc;
      char *crc250;
#line 254 "fark.c"
#line 105 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char),251);
      strcpy(crc250,"");
      mod_opensession_(&mid,crc250,&irc,250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSViv(mid)));
      free(crc250);
#line 268 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_closeModelSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_closeModelSession)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "mid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	mid = (int)SvIV(ST(0))
;
#line 128 "fark.xs"
      int  irc;
      char *crc250;
#line 289 "fark.c"
#line 131 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      strcpy(crc250,"");
      mod_closesession_(&mid,crc250, &irc, 250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 302 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_openObsSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_openObsSession)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 155 "fark.xs"
      int  sid;
      int  irc;
      char *crc250;
#line 322 "fark.c"
#line 159 "fark.xs"
      sid=0;
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      strcpy(crc250,"");
      obs_opensession_(&sid,crc250, &irc, 250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSViv(sid)));
      free(crc250);
#line 337 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_closeObsSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_closeObsSession)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	sid = (int)SvIV(ST(0))
;
#line 183 "fark.xs"
      int  irc;
      char *crc250;
#line 358 "fark.c"
#line 186 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      strcpy(crc250,"");
      obs_closesession_(&sid,crc250, &irc, 250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 371 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_openColocSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_openColocSession)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 209 "fark.xs"
      int  cid;
      int  irc;
      char *crc250;
#line 391 "fark.c"
#line 213 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char),251);
      strcpy(crc250,"");
      col_opensession_(&cid,crc250,&irc,250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSViv(cid)));
      free(crc250);
#line 405 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_closeColocSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_closeColocSession)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "cid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	cid = (int)SvIV(ST(0))
;
#line 236 "fark.xs"
      int  irc;
      char *crc250;
#line 426 "fark.c"
#line 239 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      strcpy(crc250,"");
      col_closesession_(&cid,crc250, &irc, 250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 439 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_openTableSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_openTableSession)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 261 "fark.xs"
      int  pid;
      int  irc;
      char *crc250;
#line 459 "fark.c"
#line 265 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char),251);
      strcpy(crc250,"");
      tab_opensession_(&pid,crc250,&irc,250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSViv(pid)));
      free(crc250);
#line 473 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_closeTableSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_closeTableSession)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	pid = (int)SvIV(ST(0))
;
#line 288 "fark.xs"
      int  irc;
      char *crc250;
#line 494 "fark.c"
#line 291 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      strcpy(crc250,"");
      tab_closesession_(&pid,crc250, &irc, 250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 507 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_makeModelCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_makeModelCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "sid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 313 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 527 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 317 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      path250 = calloc(sizeof(char), 250);
      strcpy(path250,path);
      mod_makecache_(&sid,path250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 547 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_makeObsCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_makeObsCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "sid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 342 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 567 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 346 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      path250 = calloc(sizeof(char), 250);
      strcpy(path250,path);
      obs_makecache_(&sid, path250,crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 587 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_loadModelCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_loadModelCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "sid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 371 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 607 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 375 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      path250 = calloc(sizeof(char), 250);
      strcpy(path250,path);
      mod_loadcache_(&sid,path250,crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 627 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setModelCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setModelCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 400 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 647 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 404 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      path250 = calloc(sizeof(char), 250);
      strcpy(path250,path);
      col_setmodcache_(&cid, path250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 667 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_loadObsCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_loadObsCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "sid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 429 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 687 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 433 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      path250 = calloc(sizeof(char), 250);
      strcpy(path250,path);
      obs_loadcache_(&sid,path250,crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 707 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 458 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 727 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 462 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      path250 = calloc(sizeof(char), 250);
      strcpy(path250,path);
      col_setobscache_(&cid, path250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 747 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearModelFileStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearModelFileStack)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "sid, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 491 "fark.xs"
      int  irc;
      char *varname;
      char *crc250;
      char* vararg;
#line 768 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 496 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      varname = calloc(sizeof(char), 80);
      if (items >= 2) {
         vararg= (char *)SvPV_nolen(ST(1));
         strcpy(varname,vararg);
      } else {
         strcpy(varname,"");
      }; 
      mod_clearfilestack_(&sid,varname, crc250, &irc, 80, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(varname);
      free(crc250);
#line 791 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearModelTargetStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearModelTargetStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 525 "fark.xs"
      int  irc;
      char *crc250;
#line 810 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 528 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      mod_cleartargetstack_(&sid,crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 825 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearDefaultStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearDefaultStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 549 "fark.xs"
      int  irc;
      char *crc250;
#line 844 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 552 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      col_cleardefaultstack_(&sid,crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 859 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushModelFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushModelFile)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "sid, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 576 "fark.xs"
      int  irc;
      char *crc250;
      int i;
      char *path250;
      char* path;
      int irc2;
#line 882 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 583 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      path250 = calloc(sizeof(char), 250);
      for (i=1; i < items; i++) {
         path= (char *)SvPV_nolen(ST(i));
         strcpy(path250,path);
	 irc2=0;
         mod_pushfile_(&sid, path250, crc250, &irc2, 250, 250);
         if(irc2 != 0) {
	    irc=irc2;
	    i=items;
         }
      }
      if (irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 908 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_peekModelFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_peekModelFile)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 619 "fark.xs"
      int maxrep;
      int nrep;
      char *rep250;
      int  irc;
      char *crc250;
      int ii;
      int lenr=250;
#line 932 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 627 "fark.xs"
	irc=0;
	crc250 = calloc(sizeof(char), 251);
        strcpy(crc250,"");
	mod_peekfilelen_(&sid,&maxrep,crc250,&irc,250);
        nrep=0;
        if (irc == 0) {
	  rep250 = calloc(sizeof(char), lenr*maxrep+1);
	  mod_peekfile_(&sid,&maxrep,&nrep,rep250,crc250,&irc,250,250);
	} else {
	  rep250 = calloc(sizeof(char), 1);
        }
	if (irc != 0 ) {
	  EXTEND(SP, 2);
	  PUSHs(sv_2mortal(newSViv(irc)));
	  PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
	} else if (nrep > 0) {
	  EXTEND(SP, 3+nrep);
	  PUSHs(sv_2mortal(newSViv(irc)));
	  PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
	  PUSHs(sv_2mortal(newSViv(nrep)));
	  for (ii=0; ii < nrep ; ii++ ) {
	    PUSHs(sv_2mortal(newSVpv(&rep250[ii*250],250)));
	  };
	} else {
	};
	free(rep250);
        free(crc250);
#line 963 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_popModelFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_popModelFile)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "sid, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	sid = (int)SvIV(ST(0))
;
#line 669 "fark.xs"
      int  irc;
      char *crc250;
      int i;
      char *path250;
      char* path;
      int irc2;
#line 988 "fark.c"
#line 676 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      strcpy(crc250,"");
      path250 = calloc(sizeof(char), 250);
      for (i=1; i < items; i++) {
         path= (char *)SvPV_nolen(ST(i));
         strcpy(path250,path);
	 irc2=0;
         mod_popfile_(&sid, path250, crc250, &irc2, 250, 250);
         if(irc2 != 0) {
	    irc=irc2;
         }
      }
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
      free(path250);
#line 1011 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setModelIndex); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setModelIndex)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "sid, trgname, varname");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 710 "fark.xs"
      int  irc;
      char *crc250;
#line 1030 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	trgname = (char *)SvPV_nolen(ST(1))
;
	char *	varname = (char *)SvPV_nolen(ST(2))
;
#line 713 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      mod_setindex_(&sid,trgname,varname,crc250, &irc, strlen(trgname),strlen(varname), 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1049 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setModelIndexLimits); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setModelIndexLimits)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "mid, smin, smax");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 737 "fark.xs"
      int  irc;
      char *crc250;
#line 1068 "fark.c"
	int	mid = (int)SvIV(ST(0))
;
	char*	smin = (char *)SvPV_nolen(ST(1))
;
	char*	smax = (char *)SvPV_nolen(ST(2))
;
#line 740 "fark.xs"
 	irc=0;
	crc250 = calloc(sizeof(char), 251);
        strcpy(crc250,"");
        mod_setindexlimits_(&mid, smin, smax, crc250, &irc, strlen(smin),strlen(smax), 250);
	EXTEND(SP, 2);
	PUSHs(sv_2mortal(newSViv(irc)));
	PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
	free(crc250);
#line 1084 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushModelTarget); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushModelTarget)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "mid, modName, var, vmin, vmax");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 767 "fark.xs"
      int  irc;
      char *crc250;
      char *m80;
      char *v80;
      char *l80;
      char *u80;
#line 1107 "fark.c"
	int	mid = (int)SvIV(ST(0))
;
	char *	modName = (char *)SvPV_nolen(ST(1))
;
	char *	var = (char *)SvPV_nolen(ST(2))
;
	char *	vmin = (char *)SvPV_nolen(ST(3))
;
	char *	vmax = (char *)SvPV_nolen(ST(4))
;
#line 774 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      m80 = calloc(sizeof(char), 80);
      v80 = calloc(sizeof(char), 80);
      l80 = calloc(sizeof(char), 80);
      u80 = calloc(sizeof(char), 80);
      strcpy(m80,modName);
      strcpy(v80,var);
      strcpy(l80,vmin);
      strcpy(u80,vmax);
      mod_pushtarget_(&mid, m80, v80, l80, u80,crc250, &irc, 80,80,80,80,250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(m80);
      free(v80);
      free(l80);
      free(u80);
      free(crc250);
#line 1142 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_addDefault); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_addDefault)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "cid, modName, val");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 811 "fark.xs"
      int  irc;
      char *crc250;
      char *m80;
      char *v80;
#line 1163 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	modName = (char *)SvPV_nolen(ST(1))
;
	char *	val = (char *)SvPV_nolen(ST(2))
;
#line 816 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      m80 = calloc(sizeof(char), 80);
      v80 = calloc(sizeof(char), 80);
      strcpy(m80,modName);
      strcpy(v80,val);
      col_adddefault_(&cid, m80, v80, crc250, &irc, 80,80,250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(m80);
      free(v80);
      free(crc250);
#line 1188 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushDefault); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushDefault)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "cid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 844 "fark.xs"
      int  irc;
      char *crc250;
#line 1207 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
#line 847 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      col_pushdefault_(&cid, crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1222 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearMatchRuleStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearMatchRuleStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "cid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 870 "fark.xs"
      int  irc;
      char *crc250;
#line 1241 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
#line 873 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      col_clearmatchstack_(&cid,crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1256 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushMatchRule); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushMatchRule)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "cid, modName, obsExpr, vmin, vmax");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 897 "fark.xs"
      int  irc;
      char *crc250;
      char *m80;
      char *o250;
      char *l80;
      char *u80;
#line 1279 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	modName = (char *)SvPV_nolen(ST(1))
;
	char *	obsExpr = (char *)SvPV_nolen(ST(2))
;
	char *	vmin = (char *)SvPV_nolen(ST(3))
;
	char *	vmax = (char *)SvPV_nolen(ST(4))
;
#line 904 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      m80 = calloc(sizeof(char), 80);
      o250 = calloc(sizeof(char), 250);
      l80 = calloc(sizeof(char), 80);
      u80 = calloc(sizeof(char), 80);
      strcpy(m80,modName);
      strcpy(o250,obsExpr);
      strcpy(l80,vmin);
      strcpy(u80,vmax);
      col_pushmatch_(&cid, m80, o250, l80, u80,crc250, &irc, 80,250,80,80,250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(m80);
      free(o250);
      free(l80);
      free(u80);
      free(crc250);
#line 1314 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_makeMatchList); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_makeMatchList)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cid, mid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 937 "fark.xs"
      int  irc;
      char *crc250;
#line 1333 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	int	mid = (int)SvIV(ST(1))
;
#line 940 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      col_makematchlist_(&cid, &mid, crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1350 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsTablePath); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsTablePath)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "oid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 964 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 1370 "fark.c"
	int	oid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 968 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      path250 = calloc(sizeof(char), 250);
      strcpy(path250,path);
      obs_settablepath_(&oid, path250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 1390 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearObsFileStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearObsFileStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "oid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 993 "fark.xs"
      int  irc;
      char *crc250;
#line 1409 "fark.c"
	int	oid = (int)SvIV(ST(0))
;
#line 996 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      obs_clearfilestack_(&oid,crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1424 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushObsFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushObsFile)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "oid, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1020 "fark.xs"
      int  irc;
      char *crc250;
      int i;
      char *path250;
      char* path;
      int irc2;
#line 1447 "fark.c"
	int	oid = (int)SvIV(ST(0))
;
#line 1027 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      path250 = calloc(sizeof(char), 250);
      for (i=1; i < items; i++) {
         path= (char *)SvPV_nolen(ST(i));
         strcpy(path250,path);
	 irc2=0;
         obs_pushfile_(&oid, path250, crc250, &irc2, 250, 250);
         if(irc2 != 0) {
	    irc=irc2;
	    i=items;
         }
      }
      if (irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 1473 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_peekObsFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_peekObsFile)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "oid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1062 "fark.xs"
      int maxrep;
      int nrep;
      char *rep250;
      int  irc;
      char *crc250;
      int ii;
      int lenr=250;
#line 1497 "fark.c"
	int	oid = (int)SvIV(ST(0))
;
#line 1070 "fark.xs"
	irc=0;
	crc250 = calloc(sizeof(char), 251);
        strcpy(crc250,"");
	obs_peekfilelen_(&oid,&maxrep,crc250,&irc,250);
        nrep=0;
        if (irc == 0) {
	  rep250 = calloc(sizeof(char), lenr*maxrep+1);
	  obs_peekfile_(&oid,&maxrep,&nrep,rep250,crc250,&irc,250,250);
	} else {
	  rep250 = calloc(sizeof(char),1);
        }
        if (irc != 0 ) {
	    EXTEND(SP, 2);
	    PUSHs(sv_2mortal(newSViv(irc)));
	    PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
	} else if (nrep > 0) {
	  EXTEND(SP, 3+nrep);
	  PUSHs(sv_2mortal(newSViv(irc)));
	  PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
	  PUSHs(sv_2mortal(newSViv(nrep)));
	  for (ii=0; ii < nrep ; ii++ ) {
	    PUSHs(sv_2mortal(newSVpv(&rep250[ii*250],250)));
	  };
	} else {
	};
	free(rep250);
        free(crc250);
#line 1528 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_popObsFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_popObsFile)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "oid, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	oid = (int)SvIV(ST(0))
;
#line 1112 "fark.xs"
      int  irc;
      char *crc250;
      int i;
      char *path250;
      char* path;
      int irc2;
#line 1553 "fark.c"
#line 1119 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      strcpy(crc250,"");
      path250 = calloc(sizeof(char), 250);
      for (i=1; i < items; i++) {
         path= (char *)SvPV_nolen(ST(i));
         strcpy(path250,path);
	 irc2=0;
         obs_popfile_(&oid, path250, crc250, &irc2, 250, 250);
         if(irc2 != 0) {
	    irc=irc2;
         }
      }
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
      free(path250);
#line 1576 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsIndexLimits); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsIndexLimits)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "sid, sindex, eindex");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1152 "fark.xs"
      int  irc;
      char *s25;
      char *e25;
      char *crc250;
#line 1597 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	sindex = (char *)SvPV_nolen(ST(1))
;
	char *	eindex = (char *)SvPV_nolen(ST(2))
;
#line 1157 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      s25 = calloc(sizeof(char), 25);
      e25 = calloc(sizeof(char), 25);
      strcpy(s25,sindex);
      strcpy(e25,eindex);
      obs_setindexlimits_(&sid,s25, e25, crc250, &irc, 25, 25, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(s25);
      free(e25);
      free(crc250);
#line 1622 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearObsTargetStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearObsTargetStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1187 "fark.xs"
      int  irc;
      char *crc250;
#line 1641 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 1190 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      obs_cleartargetstack_(&sid,crc250, &irc, 250);
      if (irc == 0) {
          strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1656 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushObsTarget); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushObsTarget)
{
    dVAR; dXSARGS;
    if (items != 7)
       croak_xs_usage(cv,  "sid, target, pos, descr, info, vmin, vmax");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1218 "fark.xs"
      int  irc;
      char *crc250;
#line 1675 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	target = (char *)SvPV_nolen(ST(1))
;
	char *	pos = (char *)SvPV_nolen(ST(2))
;
	char *	descr = (char *)SvPV_nolen(ST(3))
;
	char *	info = (char *)SvPV_nolen(ST(4))
;
	char *	vmin = (char *)SvPV_nolen(ST(5))
;
	char *	vmax = (char *)SvPV_nolen(ST(6))
;
#line 1221 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      obs_pushtarget_(&sid,target,pos,descr,info,vmin,vmax,crc250,&irc,strlen(target),strlen(pos),strlen(descr),strlen(info),strlen(vmin),strlen(vmax),250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1702 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsIndex); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsIndex)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "sid, target, expr");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1244 "fark.xs"
      int  irc;
      char *crc250;
      char *t80;
      char *e250;
#line 1723 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	target = (char *)SvPV_nolen(ST(1))
;
	char *	expr = (char *)SvPV_nolen(ST(2))
;
#line 1249 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      t80 = calloc(sizeof(char), 80);
      e250 = calloc(sizeof(char), 250);
      strcpy(t80,target);
      strcpy(e250,expr);
      obs_setindex_(&sid, t80, e250,crc250, &irc, 80,250,250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(t80);
      free(e250);
      free(crc250);
#line 1748 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsBufrType); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsBufrType)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "sid, bufrType, subType");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1279 "fark.xs"
      int  irc;
      char *crc250;
#line 1767 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	int	bufrType = (int)SvIV(ST(1))
;
	int	subType = (int)SvIV(ST(2))
;
#line 1282 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      obs_setbufrtype_(&sid, &bufrType, &subType, crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1786 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_expression); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_expression)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "exp");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1306 "fark.xs"
      char *exp250;
      int  irc;
      char *crc250;
#line 1806 "fark.c"
	char *	exp = (char *)SvPV_nolen(ST(0))
;
#line 1310 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      exp250 = calloc(sizeof(char), 250);
      strcpy(exp250,exp);
      col_expression_(exp250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(exp250,strlen(exp250))));
      free(exp250);
      free(crc250);
#line 1825 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setModelFilter); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setModelFilter)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cid, filter");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1339 "fark.xs"
      int  irc;
      char *crc250;
#line 1844 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	filter = (char *)SvPV_nolen(ST(1))
;
#line 1342 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      mod_setfilter_(&cid,filter, crc250, &irc, strlen(filter), 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1861 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsFilter); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsFilter)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cid, filter");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1364 "fark.xs"
      int  irc;
      char *crc250;
#line 1880 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	filter = (char *)SvPV_nolen(ST(1))
;
#line 1367 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      obs_setfilter_(&cid,filter, crc250, &irc, strlen(filter), 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1897 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setColocXMLFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setColocXMLFile)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pid, fn");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1389 "fark.xs"
      char *fn250;
      int  irc;
      char *crc250;
#line 1917 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	fn = (char *)SvPV_nolen(ST(1))
;
#line 1393 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      fn250 = calloc(sizeof(char), 250);
      strcpy(fn250,fn);
      col_setxmlfile_(&pid, fn250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(fn250);
      free(crc250);
#line 1937 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_getColocXMLFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_getColocXMLFile)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1418 "fark.xs"
      char *fn250;
      int  irc;
      char *crc250;
#line 1957 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1422 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      fn250 = calloc(sizeof(char), 250);
      strcpy(fn250,"");
      col_getxmlfile_(&pid, fn250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(fn250,strlen(fn250))));
      free(fn250);
      free(crc250);
#line 1976 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setShapeFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setShapeFile)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fn, cn");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1448 "fark.xs"
      char *fn250;
      char *cn11;
      int  irc;
      char *crc250;
#line 1997 "fark.c"
	char *	fn = (char *)SvPV_nolen(ST(0))
;
	char *	cn = (char *)SvPV_nolen(ST(1))
;
#line 1453 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      fn250 = calloc(sizeof(char), 250);
      cn11 = calloc(sizeof(char), 11);
      strcpy(fn250,fn);
      strcpy(cn11,cn);
      par_setshapefile_(fn250, cn11, crc250, &irc, 250, 11, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(cn11);
      free(fn250);
      free(crc250);
#line 2020 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_simplifyShapes); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_simplifyShapes)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "tol");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1481 "fark.xs"
      char *tol20;
      int  irc;
      char *crc250;
#line 2040 "fark.c"
	char *	tol = (char *)SvPV_nolen(ST(0))
;
#line 1485 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      tol20 = calloc(sizeof(char), 20);
      strcpy(tol20,tol);
      par_simplifyshapes_(tol20, crc250, &irc, 20, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(tol20);
      free(crc250);
#line 2058 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearShapeFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearShapeFile)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1509 "fark.xs"
      int  irc;
      char *crc250;
#line 2077 "fark.c"
#line 1512 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      par_clearshapefile_(crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2090 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_makeColocXML); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_makeColocXML)
{
    dVAR; dXSARGS;
    if (items != 6)
       croak_xs_usage(cv,  "cid, mid, oid, xml, test, fill");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1538 "fark.xs"
      char *xml250;
      int  irc;
      char *crc250;
      char *fill250;
#line 2111 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	int	mid = (int)SvIV(ST(1))
;
	int	oid = (int)SvIV(ST(2))
;
	char *	xml = (char *)SvPV_nolen(ST(3))
;
	int	test = (int)SvIV(ST(4))
;
	char *	fill = (char *)SvPV_nolen(ST(5))
;
#line 1543 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      fill250 = calloc(sizeof(char), 250);
      xml250 = calloc(sizeof(char), 250);
strcpy(fill250,fill);
      strcpy(xml250,xml);
      col_makexml_(&cid, &mid, &oid, xml250, &test, fill250,crc250, &irc, 250, 250,250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(xml250,strlen(xml250))));
      free(xml250);
      free(fill250);
      free(crc250);
#line 2143 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_makeTableFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_makeTableFile)
{
    dVAR; dXSARGS;
    if (items != 9)
       croak_xs_usage(cv,  "pid, cid, mid, oid, table, graph, cat, test, fill");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1577 "fark.xs"
      char *tab250;
      char *gra250;
      char *cat250;
      char *fill250;
      int  irc;
      char *crc250;
#line 2166 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	int	cid = (int)SvIV(ST(1))
;
	int	mid = (int)SvIV(ST(2))
;
	int	oid = (int)SvIV(ST(3))
;
	char *	table = (char *)SvPV_nolen(ST(4))
;
	char *	graph = (char *)SvPV_nolen(ST(5))
;
	char*	cat = (char *)SvPV_nolen(ST(6))
;
	int	test = (int)SvIV(ST(7))
;
	char *	fill = (char *)SvPV_nolen(ST(8))
;
#line 1584 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      tab250 = calloc(sizeof(char), 250);
      gra250 = calloc(sizeof(char), 250);
      cat250 = calloc(sizeof(char), 250);
      fill250 = calloc(sizeof(char), 250);
      strcpy(tab250,table);
      strcpy(gra250,graph);
      strcpy(cat250,cat);
      strcpy(fill250,fill);
      tab_maketablefile_(&pid,&cid,&mid,&oid,tab250,gra250,cat250,&test,fill250,crc250,&irc,250,250,250,250,250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 4);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(tab250,strlen(tab250))));
      PUSHs(sv_2mortal(newSVpv(gra250,strlen(gra250))));
      free(tab250);
      free(gra250);
      free(cat250);
      free(fill250);
      free(crc250);
#line 2211 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearTableFileStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearTableFileStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "tid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1620 "fark.xs"
      int  irc;
      char *crc250;
#line 2230 "fark.c"
	int	tid = (int)SvIV(ST(0))
;
#line 1623 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      tab_clearfilestack_(&tid,crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2245 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushTableFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushTableFile)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "tid, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1647 "fark.xs"
      int  irc;
      char *crc250;
      int i;
      char *path250;
      char* path;
      int irc2;
#line 2268 "fark.c"
	int	tid = (int)SvIV(ST(0))
;
#line 1654 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      path250 = calloc(sizeof(char), 250);
      for (i=1; i < items; i++) {
         path= (char *)SvPV_nolen(ST(i));
         strcpy(path250,path);
	 irc2=0;
         tab_pushfile_(&tid, path250, crc250, &irc2, 250, 250);
         if(irc2 != 0) {
	    irc=irc2;
	    i=items;
         }
      }
      if (irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 2294 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_joinTableFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_joinTableFile)
{
    dVAR; dXSARGS;
    if (items != 9)
       croak_xs_usage(cv,  "pid, cid, mid, oid, table, graph, cat, test, fill");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1693 "fark.xs"
      char *tab250;
      char *gra250;
      char *cat250;
      char *fill250;
      int  irc;
      char *crc250;
#line 2317 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	int	cid = (int)SvIV(ST(1))
;
	int	mid = (int)SvIV(ST(2))
;
	int	oid = (int)SvIV(ST(3))
;
	char *	table = (char *)SvPV_nolen(ST(4))
;
	char *	graph = (char *)SvPV_nolen(ST(5))
;
	char*	cat = (char *)SvPV_nolen(ST(6))
;
	int	test = (int)SvIV(ST(7))
;
	char *	fill = (char *)SvPV_nolen(ST(8))
;
#line 1700 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      tab250 = calloc(sizeof(char), 250);
      gra250 = calloc(sizeof(char), 250);
      cat250 = calloc(sizeof(char), 250);
      fill250 = calloc(sizeof(char), 250);
      strcpy(tab250,table);
      strcpy(gra250,graph);
      strcpy(cat250,cat);
      strcpy(fill250,fill);
      tab_jointablefile_(&pid,&cid,&mid,&oid,tab250,gra250,cat250,&test,fill250,crc250,&irc,250,250,250,250,250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 4);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(tab250,strlen(tab250))));
      PUSHs(sv_2mortal(newSVpv(gra250,strlen(gra250))));
      free(tab250);
      free(gra250);
      free(cat250);
      free(fill250);
      free(crc250);
#line 2362 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setTableType); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setTableType)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pid, type");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1736 "fark.xs"
      char *type250;
      int  irc;
      char *crc250;
#line 2382 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	type = (char *)SvPV_nolen(ST(1))
;
#line 1740 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      type250 = calloc(sizeof(char), 250);
      strcpy(type250,type);
      tab_settype_(&pid, type250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(type250);
      free(crc250);
#line 2402 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setTableFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setTableFile)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pid, fn");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1765 "fark.xs"
      char *fn250;
      int  irc;
      char *crc250;
#line 2422 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	fn = (char *)SvPV_nolen(ST(1))
;
#line 1769 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      fn250 = calloc(sizeof(char), 250);
      strcpy(fn250,fn);
      tab_settablefile_(&pid, fn250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(fn250);
      free(crc250);
#line 2442 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_getTableFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_getTableFile)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1794 "fark.xs"
      char *fn250;
      int  irc;
      char *crc250;
#line 2462 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1798 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      fn250 = calloc(sizeof(char), 250);
      strcpy(fn250,"");
      tab_gettablefile_(&pid, fn250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(fn250,strlen(fn250))));
      free(fn250);
      free(crc250);
#line 2481 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setGraphicsDir); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setGraphicsDir)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pid, fn");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1824 "fark.xs"
      char *fn250;
      int  irc;
      char *crc250;
#line 2501 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	fn = (char *)SvPV_nolen(ST(1))
;
#line 1828 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      fn250 = calloc(sizeof(char), 250);
      strcpy(fn250,fn);
      tab_setgraphicsdir_(&pid, fn250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(fn250);
      free(crc250);
#line 2521 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_getGraphicsDir); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_getGraphicsDir)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1853 "fark.xs"
      char *fn250;
      int  irc;
      char *crc250;
#line 2541 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1857 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      fn250 = calloc(sizeof(char), 250);
      strcpy(fn250,"");
      tab_getgraphicsdir_(&pid, fn250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(fn250,strlen(fn250))));
      free(fn250);
      free(crc250);
#line 2560 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_strepTableFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_strepTableFile)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1882 "fark.xs"
      int  irc;
      char *crc250;
#line 2579 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1885 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      tab_streptablefile_(&pid, crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2594 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_strepGraphicsDir); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_strepGraphicsDir)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1906 "fark.xs"
      int  irc;
      char *crc250;
#line 2613 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1909 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      tab_strepgraphicsdir_(&pid, crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2628 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearTableAttributeStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearTableAttributeStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1930 "fark.xs"
      int  irc;
      char *crc250;
#line 2647 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1933 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      tab_clearattrstack_(&pid, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2662 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushTableAttribute); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushTableAttribute)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "pid, name, value");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1957 "fark.xs"
      char *name80;
      char *value250;
      int  irc;
      char *crc250;
#line 2683 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	name = (char *)SvPV_nolen(ST(1))
;
	char *	value = (char *)SvPV_nolen(ST(2))
;
#line 1962 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      name80 = calloc(sizeof(char), 80);
      value250 = calloc(sizeof(char), 250);
      strcpy(name80,name);
      strcpy(value250,value);
      tab_pushattr_(&pid, name80, value250, crc250, &irc, 80, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(name80);
      free(value250);
      free(crc250);
#line 2708 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_limitTableColumn); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_limitTableColumn)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "pid, name, min, max");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1993 "fark.xs"
      int  irc;
      char *crc250;
#line 2727 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	name = (char *)SvPV_nolen(ST(1))
;
	char *	min = (char *)SvPV_nolen(ST(2))
;
	char *	max = (char *)SvPV_nolen(ST(3))
;
#line 1996 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      tab_limitcolumn_(&pid, name, min, max, crc250, &irc,
		       strlen(name),strlen(min),strlen(max),250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2749 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearTableSetStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearTableSetStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 2018 "fark.xs"
      int  irc;
      char *crc250;
#line 2768 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 2021 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      tab_clearsetstack_(&pid, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2783 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearTableColumn); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearTableColumn)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 2044 "fark.xs"
      int  irc;
      char *crc250;
#line 2802 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 2047 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      tab_clearcolumn_(&pid, crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2817 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushTableColumn); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushTableColumn)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "pid, name, expr");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 2072 "fark.xs"
      char *name80;
      char *exp250;
      int  irc;
      char *crc250;
#line 2838 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	name = (char *)SvPV_nolen(ST(1))
;
	char *	expr = (char *)SvPV_nolen(ST(2))
;
#line 2077 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      name80 = calloc(sizeof(char), 80);
      exp250 = calloc(sizeof(char), 250);
      strcpy(name80,name);
      strcpy(exp250,expr);
      tab_pushcolumn_(&pid, name80, exp250, crc250, &irc, 80, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(name80);
      free(exp250);
      free(crc250);
#line 2863 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushTableSet); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushTableSet)
{
    dVAR; dXSARGS;
    if (items != 6)
       croak_xs_usage(cv,  "pid, cid, mid, oid, name, legend");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 2113 "fark.xs"
      char *name80;
      char *legend250;
      int  irc;
      char *crc250;
#line 2884 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	int	cid = (int)SvIV(ST(1))
;
	int	mid = (int)SvIV(ST(2))
;
	int	oid = (int)SvIV(ST(3))
;
	char *	name = (char *)SvPV_nolen(ST(4))
;
	char *	legend = (char *)SvPV_nolen(ST(5))
;
#line 2118 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      name80 = calloc(sizeof(char), 80);
      legend250 = calloc(sizeof(char), 250);
      strcpy(name80,name);
      strcpy(legend250,legend);
      tab_pushset_(&pid, &cid, &mid, &oid, name80, legend250, crc250, &irc, 80, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(name80);
      free(legend250);
      free(crc250);
#line 2915 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setVariable); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setVariable)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "variable");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 2146 "fark.xs"
      int  irc;
      char *crc250;
#line 2934 "fark.c"
	char *	variable = (char *)SvPV_nolen(ST(0))
;
#line 2149 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      par_setvariable_(variable, crc250, &irc, strlen(variable), 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2949 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setValue); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setValue)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "value");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 2171 "fark.xs"
      int  irc;
      char *crc250;
#line 2968 "fark.c"
	int	value = (int)SvIV(ST(0))
;
#line 2174 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      par_setvalue_(&value, crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2983 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setOffset); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setOffset)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "offset");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 2196 "fark.xs"
      int  irc;
      char *crc250;
#line 3002 "fark.c"
	char *	offset = (char *)SvPV_nolen(ST(0))
;
#line 2199 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      par_setoffset_(offset, crc250, &irc, strlen(offset), 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 3017 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_getOffset); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_getOffset)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 2222 "fark.xs"
      int  irc;
      char *off25;
      char *crc250;
#line 3037 "fark.c"
#line 2226 "fark.xs"
      irc=0;
      off25 = calloc(sizeof(char), 25);
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(off25,"");
      par_getoffset_(off25, crc250, &irc, 25, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(off25,strlen(off25))));
      free(off25);
      free(crc250);
#line 3054 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setDebug); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setDebug)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "ideb");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	ideb = (int)SvIV(ST(0))
;
#line 2250 "fark.xs"
      tab_setdebug_(&ideb);
#line 3074 "fark.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_fark); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_fark)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("fark::xs_openModelSession", XS_fark_xs_openModelSession);
        newXS_deffile("fark::xs_closeModelSession", XS_fark_xs_closeModelSession);
        newXS_deffile("fark::xs_openObsSession", XS_fark_xs_openObsSession);
        newXS_deffile("fark::xs_closeObsSession", XS_fark_xs_closeObsSession);
        newXS_deffile("fark::xs_openColocSession", XS_fark_xs_openColocSession);
        newXS_deffile("fark::xs_closeColocSession", XS_fark_xs_closeColocSession);
        newXS_deffile("fark::xs_openTableSession", XS_fark_xs_openTableSession);
        newXS_deffile("fark::xs_closeTableSession", XS_fark_xs_closeTableSession);
        newXS_deffile("fark::xs_makeModelCache", XS_fark_xs_makeModelCache);
        newXS_deffile("fark::xs_makeObsCache", XS_fark_xs_makeObsCache);
        newXS_deffile("fark::xs_loadModelCache", XS_fark_xs_loadModelCache);
        newXS_deffile("fark::xs_setModelCache", XS_fark_xs_setModelCache);
        newXS_deffile("fark::xs_loadObsCache", XS_fark_xs_loadObsCache);
        newXS_deffile("fark::xs_setObsCache", XS_fark_xs_setObsCache);
        newXS_deffile("fark::xs_clearModelFileStack", XS_fark_xs_clearModelFileStack);
        newXS_deffile("fark::xs_clearModelTargetStack", XS_fark_xs_clearModelTargetStack);
        newXS_deffile("fark::xs_clearDefaultStack", XS_fark_xs_clearDefaultStack);
        newXS_deffile("fark::xs_pushModelFile", XS_fark_xs_pushModelFile);
        newXS_deffile("fark::xs_peekModelFile", XS_fark_xs_peekModelFile);
        newXS_deffile("fark::xs_popModelFile", XS_fark_xs_popModelFile);
        newXS_deffile("fark::xs_setModelIndex", XS_fark_xs_setModelIndex);
        newXS_deffile("fark::xs_setModelIndexLimits", XS_fark_xs_setModelIndexLimits);
        newXS_deffile("fark::xs_pushModelTarget", XS_fark_xs_pushModelTarget);
        newXS_deffile("fark::xs_addDefault", XS_fark_xs_addDefault);
        newXS_deffile("fark::xs_pushDefault", XS_fark_xs_pushDefault);
        newXS_deffile("fark::xs_clearMatchRuleStack", XS_fark_xs_clearMatchRuleStack);
        newXS_deffile("fark::xs_pushMatchRule", XS_fark_xs_pushMatchRule);
        newXS_deffile("fark::xs_makeMatchList", XS_fark_xs_makeMatchList);
        newXS_deffile("fark::xs_setObsTablePath", XS_fark_xs_setObsTablePath);
        newXS_deffile("fark::xs_clearObsFileStack", XS_fark_xs_clearObsFileStack);
        newXS_deffile("fark::xs_pushObsFile", XS_fark_xs_pushObsFile);
        newXS_deffile("fark::xs_peekObsFile", XS_fark_xs_peekObsFile);
        newXS_deffile("fark::xs_popObsFile", XS_fark_xs_popObsFile);
        newXS_deffile("fark::xs_setObsIndexLimits", XS_fark_xs_setObsIndexLimits);
        newXS_deffile("fark::xs_clearObsTargetStack", XS_fark_xs_clearObsTargetStack);
        newXS_deffile("fark::xs_pushObsTarget", XS_fark_xs_pushObsTarget);
        newXS_deffile("fark::xs_setObsIndex", XS_fark_xs_setObsIndex);
        newXS_deffile("fark::xs_setObsBufrType", XS_fark_xs_setObsBufrType);
        newXS_deffile("fark::xs_expression", XS_fark_xs_expression);
        newXS_deffile("fark::xs_setModelFilter", XS_fark_xs_setModelFilter);
        newXS_deffile("fark::xs_setObsFilter", XS_fark_xs_setObsFilter);
        newXS_deffile("fark::xs_setColocXMLFile", XS_fark_xs_setColocXMLFile);
        newXS_deffile("fark::xs_getColocXMLFile", XS_fark_xs_getColocXMLFile);
        newXS_deffile("fark::xs_setShapeFile", XS_fark_xs_setShapeFile);
        newXS_deffile("fark::xs_simplifyShapes", XS_fark_xs_simplifyShapes);
        newXS_deffile("fark::xs_clearShapeFile", XS_fark_xs_clearShapeFile);
        newXS_deffile("fark::xs_makeColocXML", XS_fark_xs_makeColocXML);
        newXS_deffile("fark::xs_makeTableFile", XS_fark_xs_makeTableFile);
        newXS_deffile("fark::xs_clearTableFileStack", XS_fark_xs_clearTableFileStack);
        newXS_deffile("fark::xs_pushTableFile", XS_fark_xs_pushTableFile);
        newXS_deffile("fark::xs_joinTableFile", XS_fark_xs_joinTableFile);
        newXS_deffile("fark::xs_setTableType", XS_fark_xs_setTableType);
        newXS_deffile("fark::xs_setTableFile", XS_fark_xs_setTableFile);
        newXS_deffile("fark::xs_getTableFile", XS_fark_xs_getTableFile);
        newXS_deffile("fark::xs_setGraphicsDir", XS_fark_xs_setGraphicsDir);
        newXS_deffile("fark::xs_getGraphicsDir", XS_fark_xs_getGraphicsDir);
        newXS_deffile("fark::xs_strepTableFile", XS_fark_xs_strepTableFile);
        newXS_deffile("fark::xs_strepGraphicsDir", XS_fark_xs_strepGraphicsDir);
        newXS_deffile("fark::xs_clearTableAttributeStack", XS_fark_xs_clearTableAttributeStack);
        newXS_deffile("fark::xs_pushTableAttribute", XS_fark_xs_pushTableAttribute);
        newXS_deffile("fark::xs_limitTableColumn", XS_fark_xs_limitTableColumn);
        newXS_deffile("fark::xs_clearTableSetStack", XS_fark_xs_clearTableSetStack);
        newXS_deffile("fark::xs_clearTableColumn", XS_fark_xs_clearTableColumn);
        newXS_deffile("fark::xs_pushTableColumn", XS_fark_xs_pushTableColumn);
        newXS_deffile("fark::xs_pushTableSet", XS_fark_xs_pushTableSet);
        newXS_deffile("fark::xs_setVariable", XS_fark_xs_setVariable);
        newXS_deffile("fark::xs_setValue", XS_fark_xs_setValue);
        newXS_deffile("fark::xs_setOffset", XS_fark_xs_setOffset);
        newXS_deffile("fark::xs_getOffset", XS_fark_xs_getOffset);
        newXS_deffile("fark::xs_setDebug", XS_fark_xs_setDebug);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

