/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.28 from the
 * contents of fark.xs. Do not edit this file, edit fark.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "fark.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

void mod_opensession_(int* mid, char* crc250, int* irc, int len1);
void mod_clearfilestack_(int* mid,char* varname, char* crc250,int* irc, int len1, int len2);
void mod_cleartargetstack_(int* mid,char* crc250,int* irc, int len1);
void mod_closesession_(int* mid, char*crc250, int* irc, int len1);
void mod_setindex_(int* mid, char* varname, char* crc250, int* irc, int len1, int len2, int len3);
void mod_setindexlimits_(int* mid, char* smin, char* smax, char* crc250, int* irc, int len1, int len2, int len3);
void mod_determinefileorder_(int* mid, char* crc250, int* irc, int len1);
void mod_loadcache_(int* mid,char* path,char* crc250,int* irc, int len1,int len2);
void mod_makecache_(int* mid,char* path,char* crc250,int* irc, int len1,int len2);
void mod_peekfile_(int* mid,int* maxrep,int* nrep,char* rep250,char* crc250,int* irc, int len1,int len2);
void mod_peekfilelen_(int* mid,int* maxrep,char* crc250,int* irc, int len1);
void mod_popfile_(int* mid,char* path250,char* crc250,int* irc, int len1,int len2);
void mod_pushfile_(int* mid,char* path,char* crc250,int* irc, int len1,int len2);
void mod_pushtarget_(int* mid,char* trg,char* var,char* min,char* max, char* crc250,int* irc, int len1,int len2,int len3,int len4,int len5);

void obs_opensession_(int* oid,char* crc250,int* irc, int len1);
void obs_clearfilestack_(int* oid,char* crc250,int* irc, int len1);
void obs_cleartargetstack_(int* oid,char* crc250,int* irc, int len1);
void obs_closesession_(int* oid,char* crc250,int* irc, int len1);
void obs_loadcache_(int* oid,char* path,char* crc250,int* irc, int len1,int len2);
void obs_makecache_(int* oid,char* path,char* crc250,int* irc, int len1,int len2);
void obs_peekfile_(int* oid,int* maxrep,int* nrep,char* rep250,char* crc250,int* irc,int len1,int len2);
void obs_peekfilelen_(int* oid,int* maxrep,char* crc250,int* irc, int len1);
void obs_popfile_(int* oid,char* path250,char* crc250,int* irc, int len1,int len2);
void obs_pushfile_(int* oid,char* path,char* crc250,int* irc, int len1,int len2);
void obs_pushtarget_(int* oid,char* trg,char* pos,char* descr,char* info,char* min,char* max, char* crc250,int* irc, int len1,int len2,int len3,int len4,int len5,int len6,int len7);
void obs_settablepath_(int* oid,char* path250,char* crc250,int* irc, int len1,int len2);
void obs_setindex_(int* oid,char* trg80,char* exp250, char* crc250,int* irc, int len1,int len2,int len3);
void obs_setindexlimits_(int* oid,char* s25,char* e25,char* crc250,int* irc, int len1,int len2,int len3);
void obs_setbufrtype_(int* oid,int* bufrType, int* subType, char* crc250,int* irc, int len1);

void col_opensession_(int* cid, char* crc250, int* irc, int len1);
void col_closesession_(int* cid, char* crc250, int* irc, int len1);
void col_expression_(char* exp250, char* crc250, int* irc, int len1, int len2);
void col_setmodcache_(int* cid, char* path250, char* crc250, int* irc, int len1, int len2);
void col_setobscache_(int* cid, char* path250, char* crc250, int* irc, int len1, int len2);
void col_pushdefault_(int* mid,char* crc250,int* irc, int len1);
void col_cleardefaultstack_(int* mid,char* crc250,int* irc, int len1);
void col_adddefault_(int* mid,char* trg,char* val, char* crc250,int* irc, int len1,int len2,int len3);
void col_addmatch_(int* mid, char* modName, char* obsExpr, char* smin, char* smax, char* crc250, int* irc, int len1, int len2, int len3, int len4, int len5);
void col_clearmatchstack_(int* mid, char* crc250, int* irc, int len1, int len2);

void plo_opensession_(int* pid, char* crc250, int* irc, int len1);
void plo_closesession_(int* pid, char* crc250, int* irc, int len1);
void col_setfilter_ (int* cid, char* filter250,  char* crc250, int* irc, int len1, int len2);
void plo_maketable_(int* pid, int* cid, int* mid, int* oid, char* tab250, char* gra250,char*  crc250, int* irc, int len1, int len2, int len3);
void plo_makegraphics_(int* pid, char* tab250, char* gra250, char* crc250, int* irc, int len1, int len2, int len3);
void plo_settype_(int* pid, char* type250, char* crc250, int* irc, int len1, int len2);
void plo_clearattrstack_(int* pid, char* crc250, int* irc, int len1, int len2);
void plo_pushattr_(int* pid, char* name250, char* value250, char* crc250, int* irc, int len1, int len2);
void plo_clearsetstack_(int* pid, char* crc250, int* irc, int len1, int len2);
void plo_pushset_(int* pid, int* cid, int* mid, int* oid, char* name250, char* x250, char* y250, 
		  char* legend250, char* crc250, int* irc, int len1, int len2, int len3, int len4, int len5);
void plo_settablefile_(int* pid, char* fn250, char* crc250, int* irc, int len1, int len2);
void plo_gettablefile_(int* pid, char* fn250, char* crc250, int* irc, int len1, int len2);
void plo_setgraphicsfile_(int* pid, char* fn250, char* crc250, int* irc, int len1, int len2);
void plo_getgraphicsfile_(int* pid, char* fn250, char* crc250, int* irc, int len1, int len2);
void plo_strepfiles_(int* pid, char* crc250, int* irc, int len1);

#line 76 "fark.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 220 "fark.c"

XS_EUPXS(XS_fark_xs_openModelSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_openModelSession)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 82 "fark.xs"
      int  mid;
      int  irc;
      char *crc250;
#line 235 "fark.c"
#line 86 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char),251);
      strcpy(crc250,"");
      mod_opensession_(&mid,crc250,&irc,250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSViv(mid)));
      free(crc250);
#line 249 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_closeModelSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_closeModelSession)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "mid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	mid = (int)SvIV(ST(0))
;
#line 109 "fark.xs"
      int  irc;
      char *crc250;
#line 270 "fark.c"
#line 112 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      mod_closesession_(&mid,crc250, &irc, 250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 282 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_openObsSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_openObsSession)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 135 "fark.xs"
      int  sid;
      int  irc;
      char *crc250;
#line 302 "fark.c"
#line 139 "fark.xs"
      sid=0;
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      strcpy(crc250,"");
      obs_opensession_(&sid,crc250, &irc, 250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSViv(sid)));
      free(crc250);
#line 317 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_closeObsSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_closeObsSession)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	sid = (int)SvIV(ST(0))
;
#line 163 "fark.xs"
      int  irc;
      char *crc250;
#line 338 "fark.c"
#line 166 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      obs_closesession_(&sid,crc250, &irc, 250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 350 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_openColocSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_openColocSession)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 188 "fark.xs"
      int  cid;
      int  irc;
      char *crc250;
#line 370 "fark.c"
#line 192 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char),251);
      strcpy(crc250,"");
      col_opensession_(&cid,crc250,&irc,250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSViv(cid)));
      free(crc250);
#line 384 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_closeColocSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_closeColocSession)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "cid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	cid = (int)SvIV(ST(0))
;
#line 215 "fark.xs"
      int  irc;
      char *crc250;
#line 405 "fark.c"
#line 218 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      col_closesession_(&cid,crc250, &irc, 250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 417 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_openPlotSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_openPlotSession)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 239 "fark.xs"
      int  pid;
      int  irc;
      char *crc250;
#line 437 "fark.c"
#line 243 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char),251);
      strcpy(crc250,"");
      plo_opensession_(&pid,crc250,&irc,250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSViv(pid)));
      free(crc250);
#line 451 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_closePlotSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_closePlotSession)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	pid = (int)SvIV(ST(0))
;
#line 266 "fark.xs"
      int  irc;
      char *crc250;
#line 472 "fark.c"
#line 269 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      plo_closesession_(&pid,crc250, &irc, 250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 484 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_makeModelCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_makeModelCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "sid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 290 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 504 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 294 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(path250,path);
      mod_makecache_(&sid,path250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 524 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_makeObsCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_makeObsCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "sid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 319 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 544 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 323 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(path250,path);
      obs_makecache_(&sid, path250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 564 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_loadModelCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_loadModelCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "sid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 348 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 584 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 352 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(path250,path);
      mod_loadcache_(&sid, path250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 604 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setModelCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setModelCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 377 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 624 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 381 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(path250,path);
      col_setmodcache_(&cid, path250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 644 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_loadObsCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_loadObsCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "sid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 406 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 664 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 410 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(path250,path);
      obs_loadcache_(&sid, path250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 684 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 435 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 704 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 439 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(path250,path);
      col_setobscache_(&cid, path250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 724 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearModelFileStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearModelFileStack)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "sid, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 468 "fark.xs"
      int  irc;
      char *varname;
      char *crc250;
      char* vararg;
#line 745 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 473 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      varname = calloc(sizeof(char), 80);
      strcpy(crc250,"");
      if (items >= 2) {
         vararg= (char *)SvPV_nolen(ST(1));
         strcpy(varname,vararg);
      } else {
         strcpy(varname,"");
      }; 
      mod_clearfilestack_(&sid,varname, crc250, &irc, 80, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(varname);
      free(crc250);
#line 768 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearModelTargetStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearModelTargetStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 502 "fark.xs"
      int  irc;
      char *crc250;
#line 787 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 505 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      mod_cleartargetstack_(&sid,crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 802 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearModelDefaultStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearModelDefaultStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 526 "fark.xs"
      int  irc;
      char *crc250;
#line 821 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 529 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      col_cleardefaultstack_(&sid,crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 836 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushModelFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushModelFile)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "sid, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 553 "fark.xs"
      int  irc;
      char *crc250;
      int i;
      char *path250;
      char* path;
      int irc2;
#line 859 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 560 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      for (i=1; i < items; i++) {
         path= (char *)SvPV_nolen(ST(i));
         strcpy(path250,path);
	 irc2=0;
         mod_pushfile_(&sid, path250, crc250, &irc2, 250, 250);
         if(irc2 != 0) {
	    irc=irc2;
	    i=items;
         }
      }
      if (irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 885 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_peekModelFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_peekModelFile)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 596 "fark.xs"
      int maxrep;
      int nrep;
      char *rep250;
      int  irc;
      char *crc250;
      int ii;
      int lenr=250;
#line 909 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 604 "fark.xs"
	irc=0;
	crc250 = calloc(sizeof(char), 251);
	mod_peekfilelen_(&sid,&maxrep,crc250,&irc,250);
        nrep=0;
        if (irc == 0) {
	  rep250 = calloc(sizeof(char), lenr*maxrep+1);
	  mod_peekfile_(&sid,&maxrep,&nrep,rep250,crc250,&irc,250,250);
	} else {
	  rep250 = calloc(sizeof(char), 1);
        }
	if (irc != 0 ) {
	  EXTEND(SP, 2);
	  PUSHs(sv_2mortal(newSViv(irc)));
	  PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
	} else if (nrep > 0) {
	  EXTEND(SP, 3+nrep);
	  PUSHs(sv_2mortal(newSViv(irc)));
	  PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
	  PUSHs(sv_2mortal(newSViv(nrep)));
	  for (ii=0; ii < nrep ; ii++ ) {
	    PUSHs(sv_2mortal(newSVpv(&rep250[ii*250],250)));
	  };
	} else {
	};
	free(rep250);
        free(crc250);
#line 939 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_popModelFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_popModelFile)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "sid, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	sid = (int)SvIV(ST(0))
;
#line 645 "fark.xs"
      int  irc;
      char *crc250;
      int i;
      char *path250;
      char* path;
      int irc2;
#line 964 "fark.c"
#line 652 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      for (i=1; i < items; i++) {
         path= (char *)SvPV_nolen(ST(i));
         strcpy(path250,path);
	 irc2=0;
         mod_popfile_(&sid, path250, crc250, &irc2, 250, 250);
         if(irc2 != 0) {
	    irc=irc2;
         }
      }
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
      free(path250);
#line 987 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setModelIndex); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setModelIndex)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "sid, variable");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 685 "fark.xs"
      int  irc;
      char *crc250;
#line 1006 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	variable = (char *)SvPV_nolen(ST(1))
;
#line 688 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      mod_setindex_(&sid,variable,crc250, &irc, 25, 25, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1023 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setModelIndexLimits); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setModelIndexLimits)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "mid, smin, smax");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 712 "fark.xs"
      int  irc;
      char *crc250;
#line 1042 "fark.c"
	int	mid = (int)SvIV(ST(0))
;
	char*	smin = (char *)SvPV_nolen(ST(1))
;
	char*	smax = (char *)SvPV_nolen(ST(2))
;
#line 715 "fark.xs"
	irc=0;
	crc250 = calloc(sizeof(char), 251);
 	irc=0;
        mod_setindexlimits_(&mid, smin, smax, crc250, &irc, strlen(smin),strlen(smax), 250);
	EXTEND(SP, 2);
	PUSHs(sv_2mortal(newSViv(irc)));
	PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
	free(crc250);
#line 1058 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushModelTarget); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushModelTarget)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "mid, modName, var, vmin, vmax");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 742 "fark.xs"
      int  irc;
      char *crc250;
      char *m80;
      char *v80;
      char *l80;
      char *u80;
#line 1081 "fark.c"
	int	mid = (int)SvIV(ST(0))
;
	char *	modName = (char *)SvPV_nolen(ST(1))
;
	char *	var = (char *)SvPV_nolen(ST(2))
;
	char *	vmin = (char *)SvPV_nolen(ST(3))
;
	char *	vmax = (char *)SvPV_nolen(ST(4))
;
#line 749 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      m80 = calloc(sizeof(char), 80);
      v80 = calloc(sizeof(char), 80);
      l80 = calloc(sizeof(char), 80);
      u80 = calloc(sizeof(char), 80);
      strcpy(crc250,"");
      strcpy(m80,modName);
      strcpy(v80,var);
      strcpy(l80,vmin);
      strcpy(u80,vmax);
      mod_pushtarget_(&mid, m80, v80, l80, u80,crc250, &irc, 80,80,80,80,250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(m80);
      free(v80);
      free(l80);
      free(u80);
      free(crc250);
#line 1116 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_addModelDefault); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_addModelDefault)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "cid, modName, val");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 786 "fark.xs"
      int  irc;
      char *crc250;
      char *m80;
      char *v80;
#line 1137 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	modName = (char *)SvPV_nolen(ST(1))
;
	char *	val = (char *)SvPV_nolen(ST(2))
;
#line 791 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      m80 = calloc(sizeof(char), 80);
      v80 = calloc(sizeof(char), 80);
      strcpy(crc250,"");
      strcpy(m80,modName);
      strcpy(v80,val);
      col_adddefault_(&cid, m80, v80, crc250, &irc, 80,80,250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(m80);
      free(v80);
      free(crc250);
#line 1162 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushModelDefault); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushModelDefault)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "cid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 819 "fark.xs"
      int  irc;
      char *crc250;
#line 1181 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
#line 822 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      col_pushdefault_(&cid, crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1196 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearMatchRuleStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearMatchRuleStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "cid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 845 "fark.xs"
      int  irc;
      char *crc250;
#line 1215 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
#line 848 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      col_clearmatchstack_(&cid,crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1230 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_addMatchRule); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_addMatchRule)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "cid, modName, obsExpr, vmin, vmax");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 872 "fark.xs"
      int  irc;
      char *crc250;
      char *m80;
      char *o250;
      char *l80;
      char *u80;
#line 1253 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	modName = (char *)SvPV_nolen(ST(1))
;
	char *	obsExpr = (char *)SvPV_nolen(ST(2))
;
	char *	vmin = (char *)SvPV_nolen(ST(3))
;
	char *	vmax = (char *)SvPV_nolen(ST(4))
;
#line 879 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      m80 = calloc(sizeof(char), 80);
      o250 = calloc(sizeof(char), 250);
      l80 = calloc(sizeof(char), 80);
      u80 = calloc(sizeof(char), 80);
      strcpy(crc250,"");
      strcpy(m80,modName);
      strcpy(o250,obsExpr);
      strcpy(l80,vmin);
      strcpy(u80,vmax);
      col_addmatch_(&cid, m80, o250, l80, u80,crc250, &irc, 80,250,80,80,250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(m80);
      free(o250);
      free(l80);
      free(u80);
      free(crc250);
#line 1288 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsTablePath); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsTablePath)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "oid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 915 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 1308 "fark.c"
	int	oid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 919 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(path250,path);
      obs_settablepath_(&oid, path250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 1328 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearObsFileStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearObsFileStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "oid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 944 "fark.xs"
      int  irc;
      char *crc250;
#line 1347 "fark.c"
	int	oid = (int)SvIV(ST(0))
;
#line 947 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      obs_clearfilestack_(&oid,crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1362 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushObsFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushObsFile)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "oid, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 971 "fark.xs"
      int  irc;
      char *crc250;
      int i;
      char *path250;
      char* path;
      int irc2;
#line 1385 "fark.c"
	int	oid = (int)SvIV(ST(0))
;
#line 978 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      for (i=1; i < items; i++) {
         path= (char *)SvPV_nolen(ST(i));
         strcpy(path250,path);
	 irc2=0;
         obs_pushfile_(&oid, path250, crc250, &irc2, 250, 250);
         if(irc2 != 0) {
	    irc=irc2;
	    i=items;
         }
      }
      if (irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 1411 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_peekObsFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_peekObsFile)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "oid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1013 "fark.xs"
      int maxrep;
      int nrep;
      char *rep250;
      int  irc;
      char *crc250;
      int ii;
      int lenr=250;
#line 1435 "fark.c"
	int	oid = (int)SvIV(ST(0))
;
#line 1021 "fark.xs"
	irc=0;
	crc250 = calloc(sizeof(char), 251);
	obs_peekfilelen_(&oid,&maxrep,crc250,&irc,250);
        nrep=0;
        if (irc == 0) {
	  rep250 = calloc(sizeof(char), lenr*maxrep+1);
	  obs_peekfile_(&oid,&maxrep,&nrep,rep250,crc250,&irc,250,250);
	} else {
	  rep250 = calloc(sizeof(char),1);
        }
        if (irc != 0 ) {
	    EXTEND(SP, 2);
	    PUSHs(sv_2mortal(newSViv(irc)));
	    PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
	} else if (nrep > 0) {
	  EXTEND(SP, 3+nrep);
	  PUSHs(sv_2mortal(newSViv(irc)));
	  PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
	  PUSHs(sv_2mortal(newSViv(nrep)));
	  for (ii=0; ii < nrep ; ii++ ) {
	    PUSHs(sv_2mortal(newSVpv(&rep250[ii*250],250)));
	  };
	} else {
	};
	free(rep250);
        free(crc250);
#line 1465 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_popObsFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_popObsFile)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "oid, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	oid = (int)SvIV(ST(0))
;
#line 1062 "fark.xs"
      int  irc;
      char *crc250;
      int i;
      char *path250;
      char* path;
      int irc2;
#line 1490 "fark.c"
#line 1069 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      for (i=1; i < items; i++) {
         path= (char *)SvPV_nolen(ST(i));
         strcpy(path250,path);
	 irc2=0;
         obs_popfile_(&oid, path250, crc250, &irc2, 250, 250);
         if(irc2 != 0) {
	    irc=irc2;
         }
      }
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
      free(path250);
#line 1513 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsIndexLimits); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsIndexLimits)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "sid, sindex, eindex");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1102 "fark.xs"
      int  irc;
      char *s25;
      char *e25;
      char *crc250;
#line 1534 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	sindex = (char *)SvPV_nolen(ST(1))
;
	char *	eindex = (char *)SvPV_nolen(ST(2))
;
#line 1107 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      s25 = calloc(sizeof(char), 25);
      e25 = calloc(sizeof(char), 25);
      strcpy(crc250,"");
      strcpy(s25,sindex);
      strcpy(e25,eindex);
      obs_setindexlimits_(&sid,s25, e25, crc250, &irc, 25, 25, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(s25);
      free(e25);
      free(crc250);
#line 1559 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearObsTargetStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearObsTargetStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1137 "fark.xs"
      int  irc;
      char *crc250;
#line 1578 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 1140 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      obs_cleartargetstack_(&sid,crc250, &irc, 250);
      if (irc == 0) {
          strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1593 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushObsTarget); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushObsTarget)
{
    dVAR; dXSARGS;
    if (items != 7)
       croak_xs_usage(cv,  "sid, target, pos, descr, info, vmin, vmax");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1168 "fark.xs"
      int  irc;
      char *crc250;
#line 1612 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	target = (char *)SvPV_nolen(ST(1))
;
	char *	pos = (char *)SvPV_nolen(ST(2))
;
	char *	descr = (char *)SvPV_nolen(ST(3))
;
	char *	info = (char *)SvPV_nolen(ST(4))
;
	char *	vmin = (char *)SvPV_nolen(ST(5))
;
	char *	vmax = (char *)SvPV_nolen(ST(6))
;
#line 1171 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      obs_pushtarget_(&sid,target,pos,descr,info,vmin,vmax,crc250,&irc,strlen(target),strlen(pos),strlen(descr),strlen(info),strlen(vmin),strlen(vmax),250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1639 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsIndex); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsIndex)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "sid, target, expr");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1194 "fark.xs"
      int  irc;
      char *crc250;
      char *t80;
      char *e250;
#line 1660 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	target = (char *)SvPV_nolen(ST(1))
;
	char *	expr = (char *)SvPV_nolen(ST(2))
;
#line 1199 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      t80 = calloc(sizeof(char), 80);
      e250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(t80,target);
      strcpy(e250,expr);
      obs_setindex_(&sid, t80, e250,crc250, &irc, 80,250,250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(t80);
      free(e250);
      free(crc250);
#line 1685 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsBufrType); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsBufrType)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "sid, bufrType, subType");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1229 "fark.xs"
      int  irc;
      char *crc250;
#line 1704 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	int	bufrType = (int)SvIV(ST(1))
;
	int	subType = (int)SvIV(ST(2))
;
#line 1232 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      obs_setbufrtype_(&sid, &bufrType, &subType, crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1723 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_expression); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_expression)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "exp");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1256 "fark.xs"
      char *exp250;
      int  irc;
      char *crc250;
#line 1743 "fark.c"
	char *	exp = (char *)SvPV_nolen(ST(0))
;
#line 1260 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      exp250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(exp250,exp);
      col_expression_(exp250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(exp250,strlen(exp250))));
      free(exp250);
      free(crc250);
#line 1762 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setColocFilter); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setColocFilter)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cid, filter");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1289 "fark.xs"
      char *filter250;
      int  irc;
      char *crc250;
#line 1782 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	filter = (char *)SvPV_nolen(ST(1))
;
#line 1293 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      filter250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(filter250,filter);
      col_setfilter_(&cid,filter250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(filter250);
      free(crc250);
#line 1802 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_makePlotTable); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_makePlotTable)
{
    dVAR; dXSARGS;
    if (items != 6)
       croak_xs_usage(cv,  "pid, cid, mid, oid, table, graph");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1321 "fark.xs"
      char *tab250;
      char *gra250;
      int  irc;
      char *crc250;
#line 1823 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	int	cid = (int)SvIV(ST(1))
;
	int	mid = (int)SvIV(ST(2))
;
	int	oid = (int)SvIV(ST(3))
;
	char *	table = (char *)SvPV_nolen(ST(4))
;
	char *	graph = (char *)SvPV_nolen(ST(5))
;
#line 1326 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      tab250 = calloc(sizeof(char), 250);
      gra250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(tab250,table);
      strcpy(gra250,graph);
      plo_maketable_(&pid, &cid, &mid, &oid, tab250, gra250, crc250, &irc, 250, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 4);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(tab250,strlen(tab250))));
      PUSHs(sv_2mortal(newSVpv(gra250,strlen(gra250))));
      free(tab250);
      free(gra250);
      free(crc250);
#line 1856 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_makePlotGraphics); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_makePlotGraphics)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "pid, table, graph");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1359 "fark.xs"
      char *tab250;
      char *gra250;
      int  irc;
      char *crc250;
#line 1877 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	table = (char *)SvPV_nolen(ST(1))
;
	char *	graph = (char *)SvPV_nolen(ST(2))
;
#line 1364 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      tab250 = calloc(sizeof(char), 250);
      gra250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(tab250,table);
      strcpy(gra250,graph);
      plo_makegraphics_(&pid, tab250, gra250, crc250, &irc, 250, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(tab250);
      free(gra250);
      free(crc250);
#line 1902 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setPlotType); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setPlotType)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pid, type");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1392 "fark.xs"
      char *type250;
      int  irc;
      char *crc250;
#line 1922 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	type = (char *)SvPV_nolen(ST(1))
;
#line 1396 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      type250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(type250,type);
      plo_settype_(&pid, type250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(type250);
      free(crc250);
#line 1942 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setPlotTableFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setPlotTableFile)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pid, fn");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1421 "fark.xs"
      char *fn250;
      int  irc;
      char *crc250;
#line 1962 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	fn = (char *)SvPV_nolen(ST(1))
;
#line 1425 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      fn250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(fn250,fn);
      plo_settablefile_(&pid, fn250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(fn250);
      free(crc250);
#line 1982 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_getPlotTableFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_getPlotTableFile)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1450 "fark.xs"
      char *fn250;
      int  irc;
      char *crc250;
#line 2002 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1454 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      fn250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(fn250,"");
      plo_gettablefile_(&pid, fn250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(fn250,strlen(fn250))));
      free(fn250);
      free(crc250);
#line 2021 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setPlotGraphicsFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setPlotGraphicsFile)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pid, fn");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1480 "fark.xs"
      char *fn250;
      int  irc;
      char *crc250;
#line 2041 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	fn = (char *)SvPV_nolen(ST(1))
;
#line 1484 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      fn250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(fn250,fn);
      plo_setgraphicsfile_(&pid, fn250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(fn250);
      free(crc250);
#line 2061 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_getPlotGraphicsFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_getPlotGraphicsFile)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1509 "fark.xs"
      char *fn250;
      int  irc;
      char *crc250;
#line 2081 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1513 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      fn250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(fn250,"");
      plo_getgraphicsfile_(&pid, fn250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(fn250,strlen(fn250))));
      free(fn250);
      free(crc250);
#line 2100 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_strepPlotFiles); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_strepPlotFiles)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1538 "fark.xs"
      int  irc;
      char *crc250;
#line 2119 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1541 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      plo_strepfiles_(&pid, crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2134 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearPlotAttributeStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearPlotAttributeStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1562 "fark.xs"
      int  irc;
      char *crc250;
#line 2153 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1565 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      plo_clearattrstack_(&pid, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2168 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushPlotAttribute); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushPlotAttribute)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "pid, name, value");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1589 "fark.xs"
      char *name250;
      char *value250;
      int  irc;
      char *crc250;
#line 2189 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	name = (char *)SvPV_nolen(ST(1))
;
	char *	value = (char *)SvPV_nolen(ST(2))
;
#line 1594 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      name250 = calloc(sizeof(char), 250);
      value250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(name250,name);
      strcpy(value250,value);
      plo_pushattr_(&pid, name250, value250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(name250);
      free(value250);
      free(crc250);
#line 2214 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearPlotSetStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearPlotSetStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1621 "fark.xs"
      int  irc;
      char *crc250;
#line 2233 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1624 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      plo_clearsetstack_(&pid, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2248 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushPlotSet); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushPlotSet)
{
    dVAR; dXSARGS;
    if (items != 8)
       croak_xs_usage(cv,  "pid, cid, mid, oid, name, x, y, legend");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1654 "fark.xs"
      char *name250;
      char *x250;
      char *y250;
      char *legend250;
      int  irc;
      char *crc250;
#line 2271 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	int	cid = (int)SvIV(ST(1))
;
	int	mid = (int)SvIV(ST(2))
;
	int	oid = (int)SvIV(ST(3))
;
	char *	name = (char *)SvPV_nolen(ST(4))
;
	char *	x = (char *)SvPV_nolen(ST(5))
;
	char *	y = (char *)SvPV_nolen(ST(6))
;
	char *	legend = (char *)SvPV_nolen(ST(7))
;
#line 1661 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      name250 = calloc(sizeof(char), 250);
      x250 = calloc(sizeof(char), 250);
      y250 = calloc(sizeof(char), 250);
      legend250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(name250,name);
      strcpy(x250,x);
      strcpy(y250,y);
      strcpy(legend250,legend);
      plo_pushset_(&pid, &cid, &mid, &oid, name250, x250, y250, legend250, crc250, &irc, 250, 250, 250, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(name250);
      free(x250);
      free(y250);
      free(legend250);
      free(crc250);
#line 2312 "fark.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_fark); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_fark)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("fark::xs_openModelSession", XS_fark_xs_openModelSession);
        newXS_deffile("fark::xs_closeModelSession", XS_fark_xs_closeModelSession);
        newXS_deffile("fark::xs_openObsSession", XS_fark_xs_openObsSession);
        newXS_deffile("fark::xs_closeObsSession", XS_fark_xs_closeObsSession);
        newXS_deffile("fark::xs_openColocSession", XS_fark_xs_openColocSession);
        newXS_deffile("fark::xs_closeColocSession", XS_fark_xs_closeColocSession);
        newXS_deffile("fark::xs_openPlotSession", XS_fark_xs_openPlotSession);
        newXS_deffile("fark::xs_closePlotSession", XS_fark_xs_closePlotSession);
        newXS_deffile("fark::xs_makeModelCache", XS_fark_xs_makeModelCache);
        newXS_deffile("fark::xs_makeObsCache", XS_fark_xs_makeObsCache);
        newXS_deffile("fark::xs_loadModelCache", XS_fark_xs_loadModelCache);
        newXS_deffile("fark::xs_setModelCache", XS_fark_xs_setModelCache);
        newXS_deffile("fark::xs_loadObsCache", XS_fark_xs_loadObsCache);
        newXS_deffile("fark::xs_setObsCache", XS_fark_xs_setObsCache);
        newXS_deffile("fark::xs_clearModelFileStack", XS_fark_xs_clearModelFileStack);
        newXS_deffile("fark::xs_clearModelTargetStack", XS_fark_xs_clearModelTargetStack);
        newXS_deffile("fark::xs_clearModelDefaultStack", XS_fark_xs_clearModelDefaultStack);
        newXS_deffile("fark::xs_pushModelFile", XS_fark_xs_pushModelFile);
        newXS_deffile("fark::xs_peekModelFile", XS_fark_xs_peekModelFile);
        newXS_deffile("fark::xs_popModelFile", XS_fark_xs_popModelFile);
        newXS_deffile("fark::xs_setModelIndex", XS_fark_xs_setModelIndex);
        newXS_deffile("fark::xs_setModelIndexLimits", XS_fark_xs_setModelIndexLimits);
        newXS_deffile("fark::xs_pushModelTarget", XS_fark_xs_pushModelTarget);
        newXS_deffile("fark::xs_addModelDefault", XS_fark_xs_addModelDefault);
        newXS_deffile("fark::xs_pushModelDefault", XS_fark_xs_pushModelDefault);
        newXS_deffile("fark::xs_clearMatchRuleStack", XS_fark_xs_clearMatchRuleStack);
        newXS_deffile("fark::xs_addMatchRule", XS_fark_xs_addMatchRule);
        newXS_deffile("fark::xs_setObsTablePath", XS_fark_xs_setObsTablePath);
        newXS_deffile("fark::xs_clearObsFileStack", XS_fark_xs_clearObsFileStack);
        newXS_deffile("fark::xs_pushObsFile", XS_fark_xs_pushObsFile);
        newXS_deffile("fark::xs_peekObsFile", XS_fark_xs_peekObsFile);
        newXS_deffile("fark::xs_popObsFile", XS_fark_xs_popObsFile);
        newXS_deffile("fark::xs_setObsIndexLimits", XS_fark_xs_setObsIndexLimits);
        newXS_deffile("fark::xs_clearObsTargetStack", XS_fark_xs_clearObsTargetStack);
        newXS_deffile("fark::xs_pushObsTarget", XS_fark_xs_pushObsTarget);
        newXS_deffile("fark::xs_setObsIndex", XS_fark_xs_setObsIndex);
        newXS_deffile("fark::xs_setObsBufrType", XS_fark_xs_setObsBufrType);
        newXS_deffile("fark::xs_expression", XS_fark_xs_expression);
        newXS_deffile("fark::xs_setColocFilter", XS_fark_xs_setColocFilter);
        newXS_deffile("fark::xs_makePlotTable", XS_fark_xs_makePlotTable);
        newXS_deffile("fark::xs_makePlotGraphics", XS_fark_xs_makePlotGraphics);
        newXS_deffile("fark::xs_setPlotType", XS_fark_xs_setPlotType);
        newXS_deffile("fark::xs_setPlotTableFile", XS_fark_xs_setPlotTableFile);
        newXS_deffile("fark::xs_getPlotTableFile", XS_fark_xs_getPlotTableFile);
        newXS_deffile("fark::xs_setPlotGraphicsFile", XS_fark_xs_setPlotGraphicsFile);
        newXS_deffile("fark::xs_getPlotGraphicsFile", XS_fark_xs_getPlotGraphicsFile);
        newXS_deffile("fark::xs_strepPlotFiles", XS_fark_xs_strepPlotFiles);
        newXS_deffile("fark::xs_clearPlotAttributeStack", XS_fark_xs_clearPlotAttributeStack);
        newXS_deffile("fark::xs_pushPlotAttribute", XS_fark_xs_pushPlotAttribute);
        newXS_deffile("fark::xs_clearPlotSetStack", XS_fark_xs_clearPlotSetStack);
        newXS_deffile("fark::xs_pushPlotSet", XS_fark_xs_pushPlotSet);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

