/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.28 from the
 * contents of fark.xs. Do not edit this file, edit fark.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "fark.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

void mod_opensession_(int* mid, char* crc250, int* irc, int len1);
void mod_clearfilestack_(int* mid,char* varname, char* crc250,int* irc, int len1, int len2);
void mod_cleartargetstack_(int* mid,char* crc250,int* irc, int len1);
void mod_closesession_(int* mid, char*crc250, int* irc, int len1);
void mod_setindex_(int* mid, char* trgname, char* varname, char* crc250, int* irc, int len1, int len2, int len3);
void mod_setindexlimits_(int* mid, char* smin, char* smax, char* crc250, int* irc, int len1, int len2, int len3);
void mod_determinefileorder_(int* mid, char* crc250, int* irc, int len1);
void mod_loadcache_(int* mid,char* path,char* crc250,int* irc, int len1,int len2);
void mod_makecache_(int* mid,char* path,char* crc250,int* irc, int len1,int len2);
void mod_peekfile_(int* mid,int* maxrep,int* nrep,char* rep250,char* crc250,int* irc, int len1,int len2);
void mod_peekfilelen_(int* mid,int* maxrep,char* crc250,int* irc, int len1);
void mod_popfile_(int* mid,char* path250,char* crc250,int* irc, int len1,int len2);
void mod_pushfile_(int* mid,char* path,char* crc250,int* irc, int len1,int len2);
void mod_pushtarget_(int* mid,char* trg,char* var,char* min,char* max, char* crc250,int* irc, int len1,int len2,int len3,int len4,int len5);
void mod_setfilter_ (int* cid, char* flt,  char* crc250, int* irc, int len1, int len2);

void obs_opensession_(int* oid,char* crc250,int* irc, int len1);
void obs_clearfilestack_(int* oid,char* crc250,int* irc, int len1);
void obs_cleartargetstack_(int* oid,char* crc250,int* irc, int len1);
void obs_closesession_(int* oid,char* crc250,int* irc, int len1);
void obs_loadcache_(int* oid,char* path,char* crc250,int* irc, int len1,int len2);
void obs_makecache_(int* oid,char* path,char* crc250,int* irc, int len1,int len2);
void obs_peekfile_(int* oid,int* maxrep,int* nrep,char* rep250,char* crc250,int* irc,int len1,int len2);
void obs_peekfilelen_(int* oid,int* maxrep,char* crc250,int* irc, int len1);
void obs_popfile_(int* oid,char* path250,char* crc250,int* irc, int len1,int len2);
void obs_pushfile_(int* oid,char* path,char* crc250,int* irc, int len1,int len2);
void obs_pushtarget_(int* oid,char* trg,char* pos,char* descr,char* info,char* min,char* max, char* crc250,int* irc, int len1,int len2,int len3,int len4,int len5,int len6,int len7);
void obs_settablepath_(int* oid,char* path250,char* crc250,int* irc, int len1,int len2);
void obs_setindex_(int* oid,char* trg80,char* exp250, char* crc250,int* irc, int len1,int len2,int len3);
void obs_setindexlimits_(int* oid,char* s25,char* e25,char* crc250,int* irc, int len1,int len2,int len3);
void obs_setbufrtype_(int* oid,int* bufrType, int* subType, char* crc250,int* irc, int len1);
void obs_setfilter_ (int* cid, char* flt,  char* crc250, int* irc, int len1, int len2);

void col_opensession_(int* cid, char* crc250, int* irc, int len1);
void col_closesession_(int* cid, char* crc250, int* irc, int len1);
void col_expression_(char* exp250, char* crc250, int* irc, int len1, int len2);
void col_setmodcache_(int* cid, char* path250, char* crc250, int* irc, int len1, int len2);
void col_setobscache_(int* cid, char* path250, char* crc250, int* irc, int len1, int len2);
void col_pushdefault_(int* cid,char* crc250,int* irc, int len1);
void col_cleardefaultstack_(int* cid,char* crc250,int* irc, int len1);
void col_adddefault_(int* cid,char* trg,char* val, char* crc250,int* irc, int len1,int len2,int len3);
void col_pushmatch_(int* cid, char* modName, char* obsExpr, char* smin, char* smax, char* crc250, int* irc, int len1, int len2, int len3, int len4, int len5);
void col_makematchlist_(int* cid, int* mid, char* crc250, int* irc, int len1);
void col_clearmatchstack_(int* mid, char* crc250, int* irc, int len1, int len2);
void col_makexml_(int* cid, int* mid, int* oid, char* xml250, int* test,char* fill250, char*  crc250, int* irc, int len1, int len2, int len3);
void col_setxmlfile_(int* pid, char* fn250, char* crc250, int* irc, int len1, int len2);
void col_getxmlfile_(int* pid, char* fn250, char* crc250, int* irc, int len1, int len2);

void par_setshapefile_(char* fn250, char* cname11, char* crc250, int* irc, int len1, int len2, int len3);
void par_simplifyshapes_(char* tol20, char* crc250, int* irc, int len1, int len2);
void par_clearshapefile_(char* crc250, int* irc, int len1);

void plo_opensession_(int* pid, char* crc250, int* irc, int len1);
void plo_closesession_(int* pid, char* crc250, int* irc, int len1);
void plo_maketable_(int* pid, int* cid, int* mid, int* oid, char* tab250, char* gra250,char* cat250,int* test,char* fill250,char*  crc250, int* irc, int len1, int len2, int len3, int len4, int len5);
void plo_settype_(int* pid, char* type250, char* crc250, int* irc, int len1, int len2);
void plo_clearattrstack_(int* pid, char* crc250, int* irc, int len1, int len2);
void plo_pushattr_(int* pid, char* name80, char* value250, char* crc250, int* irc, int len1, int len2, int len3);
void plo_clearsetstack_(int* pid, char* crc250, int* irc, int len1, int len2);
void plo_clearcolumn_(int* pid, char* crc250, int* irc, int len1);
void plo_pushcolumn_(int* pid, char* name80, char* exp250, char* crc250, int* irc, int len1, int len2, int len3);
void plo_pushset_(int* pid, int* cid, int* mid, int* oid, char* name250, char* legend250, char* crc250, int* irc, int len1, int len2, int len3);
void plo_settablefile_(int* pid, char* fn250, char* crc250, int* irc, int len1, int len2);
void plo_gettablefile_(int* pid, char* fn250, char* crc250, int* irc, int len1, int len2);
void plo_setgraphicsfile_(int* pid, char* fn250, char* crc250, int* irc, int len1, int len2);
void plo_getgraphicsfile_(int* pid, char* fn250, char* crc250, int* irc, int len1, int len2);
void plo_strepfiles_(int* pid, char* crc250, int* irc, int len1);
void plo_setdebug_(int* ideb);

#line 86 "fark.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 230 "fark.c"

XS_EUPXS(XS_fark_xs_openModelSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_openModelSession)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 92 "fark.xs"
      int  mid;
      int  irc;
      char *crc250;
#line 245 "fark.c"
#line 96 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char),251);
      strcpy(crc250,"");
      mod_opensession_(&mid,crc250,&irc,250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSViv(mid)));
      free(crc250);
#line 259 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_closeModelSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_closeModelSession)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "mid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	mid = (int)SvIV(ST(0))
;
#line 119 "fark.xs"
      int  irc;
      char *crc250;
#line 280 "fark.c"
#line 122 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      mod_closesession_(&mid,crc250, &irc, 250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 292 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_openObsSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_openObsSession)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 145 "fark.xs"
      int  sid;
      int  irc;
      char *crc250;
#line 312 "fark.c"
#line 149 "fark.xs"
      sid=0;
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      strcpy(crc250,"");
      obs_opensession_(&sid,crc250, &irc, 250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSViv(sid)));
      free(crc250);
#line 327 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_closeObsSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_closeObsSession)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	sid = (int)SvIV(ST(0))
;
#line 173 "fark.xs"
      int  irc;
      char *crc250;
#line 348 "fark.c"
#line 176 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      obs_closesession_(&sid,crc250, &irc, 250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 360 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_openColocSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_openColocSession)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 198 "fark.xs"
      int  cid;
      int  irc;
      char *crc250;
#line 380 "fark.c"
#line 202 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char),251);
      strcpy(crc250,"");
      col_opensession_(&cid,crc250,&irc,250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSViv(cid)));
      free(crc250);
#line 394 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_closeColocSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_closeColocSession)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "cid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	cid = (int)SvIV(ST(0))
;
#line 225 "fark.xs"
      int  irc;
      char *crc250;
#line 415 "fark.c"
#line 228 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      col_closesession_(&cid,crc250, &irc, 250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 427 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_openPlotSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_openPlotSession)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 249 "fark.xs"
      int  pid;
      int  irc;
      char *crc250;
#line 447 "fark.c"
#line 253 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char),251);
      strcpy(crc250,"");
      plo_opensession_(&pid,crc250,&irc,250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSViv(pid)));
      free(crc250);
#line 461 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_closePlotSession); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_closePlotSession)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	pid = (int)SvIV(ST(0))
;
#line 276 "fark.xs"
      int  irc;
      char *crc250;
#line 482 "fark.c"
#line 279 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      plo_closesession_(&pid,crc250, &irc, 250);
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 494 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_makeModelCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_makeModelCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "sid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 300 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 514 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 304 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(path250,path);
      mod_makecache_(&sid,path250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 534 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_makeObsCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_makeObsCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "sid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 329 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 554 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 333 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(path250,path);
      obs_makecache_(&sid, path250,crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 574 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_loadModelCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_loadModelCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "sid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 358 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 594 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 362 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(path250,path);
      mod_loadcache_(&sid,path250,crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 614 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setModelCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setModelCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 387 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 634 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 391 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(path250,path);
      col_setmodcache_(&cid, path250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 654 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_loadObsCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_loadObsCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "sid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 416 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 674 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 420 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(path250,path);
      obs_loadcache_(&sid,path250,crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 694 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsCache); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsCache)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 445 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 714 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 449 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(path250,path);
      col_setobscache_(&cid, path250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 734 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearModelFileStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearModelFileStack)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "sid, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 478 "fark.xs"
      int  irc;
      char *varname;
      char *crc250;
      char* vararg;
#line 755 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 483 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      varname = calloc(sizeof(char), 80);
      strcpy(crc250,"");
      if (items >= 2) {
         vararg= (char *)SvPV_nolen(ST(1));
         strcpy(varname,vararg);
      } else {
         strcpy(varname,"");
      }; 
      mod_clearfilestack_(&sid,varname, crc250, &irc, 80, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(varname);
      free(crc250);
#line 778 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearModelTargetStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearModelTargetStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 512 "fark.xs"
      int  irc;
      char *crc250;
#line 797 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 515 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      mod_cleartargetstack_(&sid,crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 812 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearDefaultStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearDefaultStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 536 "fark.xs"
      int  irc;
      char *crc250;
#line 831 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 539 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      col_cleardefaultstack_(&sid,crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 846 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushModelFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushModelFile)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "sid, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 563 "fark.xs"
      int  irc;
      char *crc250;
      int i;
      char *path250;
      char* path;
      int irc2;
#line 869 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 570 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      for (i=1; i < items; i++) {
         path= (char *)SvPV_nolen(ST(i));
         strcpy(path250,path);
	 irc2=0;
         mod_pushfile_(&sid, path250, crc250, &irc2, 250, 250);
         if(irc2 != 0) {
	    irc=irc2;
	    i=items;
         }
      }
      if (irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 895 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_peekModelFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_peekModelFile)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 606 "fark.xs"
      int maxrep;
      int nrep;
      char *rep250;
      int  irc;
      char *crc250;
      int ii;
      int lenr=250;
#line 919 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 614 "fark.xs"
	irc=0;
	crc250 = calloc(sizeof(char), 251);
	mod_peekfilelen_(&sid,&maxrep,crc250,&irc,250);
        nrep=0;
        if (irc == 0) {
	  rep250 = calloc(sizeof(char), lenr*maxrep+1);
	  mod_peekfile_(&sid,&maxrep,&nrep,rep250,crc250,&irc,250,250);
	} else {
	  rep250 = calloc(sizeof(char), 1);
        }
	if (irc != 0 ) {
	  EXTEND(SP, 2);
	  PUSHs(sv_2mortal(newSViv(irc)));
	  PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
	} else if (nrep > 0) {
	  EXTEND(SP, 3+nrep);
	  PUSHs(sv_2mortal(newSViv(irc)));
	  PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
	  PUSHs(sv_2mortal(newSViv(nrep)));
	  for (ii=0; ii < nrep ; ii++ ) {
	    PUSHs(sv_2mortal(newSVpv(&rep250[ii*250],250)));
	  };
	} else {
	};
	free(rep250);
        free(crc250);
#line 949 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_popModelFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_popModelFile)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "sid, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	sid = (int)SvIV(ST(0))
;
#line 655 "fark.xs"
      int  irc;
      char *crc250;
      int i;
      char *path250;
      char* path;
      int irc2;
#line 974 "fark.c"
#line 662 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      for (i=1; i < items; i++) {
         path= (char *)SvPV_nolen(ST(i));
         strcpy(path250,path);
	 irc2=0;
         mod_popfile_(&sid, path250, crc250, &irc2, 250, 250);
         if(irc2 != 0) {
	    irc=irc2;
         }
      }
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
      free(path250);
#line 997 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setModelIndex); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setModelIndex)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "sid, trgname, varname");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 696 "fark.xs"
      int  irc;
      char *crc250;
#line 1016 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	trgname = (char *)SvPV_nolen(ST(1))
;
	char *	varname = (char *)SvPV_nolen(ST(2))
;
#line 699 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      mod_setindex_(&sid,trgname,varname,crc250, &irc, 25, 25, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1035 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setModelIndexLimits); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setModelIndexLimits)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "mid, smin, smax");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 723 "fark.xs"
      int  irc;
      char *crc250;
#line 1054 "fark.c"
	int	mid = (int)SvIV(ST(0))
;
	char*	smin = (char *)SvPV_nolen(ST(1))
;
	char*	smax = (char *)SvPV_nolen(ST(2))
;
#line 726 "fark.xs"
	irc=0;
	crc250 = calloc(sizeof(char), 251);
 	irc=0;
        mod_setindexlimits_(&mid, smin, smax, crc250, &irc, strlen(smin),strlen(smax), 250);
	EXTEND(SP, 2);
	PUSHs(sv_2mortal(newSViv(irc)));
	PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
	free(crc250);
#line 1070 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushModelTarget); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushModelTarget)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "mid, modName, var, vmin, vmax");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 753 "fark.xs"
      int  irc;
      char *crc250;
      char *m80;
      char *v80;
      char *l80;
      char *u80;
#line 1093 "fark.c"
	int	mid = (int)SvIV(ST(0))
;
	char *	modName = (char *)SvPV_nolen(ST(1))
;
	char *	var = (char *)SvPV_nolen(ST(2))
;
	char *	vmin = (char *)SvPV_nolen(ST(3))
;
	char *	vmax = (char *)SvPV_nolen(ST(4))
;
#line 760 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      m80 = calloc(sizeof(char), 80);
      v80 = calloc(sizeof(char), 80);
      l80 = calloc(sizeof(char), 80);
      u80 = calloc(sizeof(char), 80);
      strcpy(crc250,"");
      strcpy(m80,modName);
      strcpy(v80,var);
      strcpy(l80,vmin);
      strcpy(u80,vmax);
      mod_pushtarget_(&mid, m80, v80, l80, u80,crc250, &irc, 80,80,80,80,250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(m80);
      free(v80);
      free(l80);
      free(u80);
      free(crc250);
#line 1128 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_addDefault); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_addDefault)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "cid, modName, val");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 797 "fark.xs"
      int  irc;
      char *crc250;
      char *m80;
      char *v80;
#line 1149 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	modName = (char *)SvPV_nolen(ST(1))
;
	char *	val = (char *)SvPV_nolen(ST(2))
;
#line 802 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      m80 = calloc(sizeof(char), 80);
      v80 = calloc(sizeof(char), 80);
      strcpy(crc250,"");
      strcpy(m80,modName);
      strcpy(v80,val);
      col_adddefault_(&cid, m80, v80, crc250, &irc, 80,80,250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(m80);
      free(v80);
      free(crc250);
#line 1174 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushDefault); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushDefault)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "cid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 830 "fark.xs"
      int  irc;
      char *crc250;
#line 1193 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
#line 833 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      col_pushdefault_(&cid, crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1208 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearMatchRuleStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearMatchRuleStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "cid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 856 "fark.xs"
      int  irc;
      char *crc250;
#line 1227 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
#line 859 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      col_clearmatchstack_(&cid,crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1242 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushMatchRule); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushMatchRule)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "cid, modName, obsExpr, vmin, vmax");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 883 "fark.xs"
      int  irc;
      char *crc250;
      char *m80;
      char *o250;
      char *l80;
      char *u80;
#line 1265 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	modName = (char *)SvPV_nolen(ST(1))
;
	char *	obsExpr = (char *)SvPV_nolen(ST(2))
;
	char *	vmin = (char *)SvPV_nolen(ST(3))
;
	char *	vmax = (char *)SvPV_nolen(ST(4))
;
#line 890 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      m80 = calloc(sizeof(char), 80);
      o250 = calloc(sizeof(char), 250);
      l80 = calloc(sizeof(char), 80);
      u80 = calloc(sizeof(char), 80);
      strcpy(crc250,"");
      strcpy(m80,modName);
      strcpy(o250,obsExpr);
      strcpy(l80,vmin);
      strcpy(u80,vmax);
      col_pushmatch_(&cid, m80, o250, l80, u80,crc250, &irc, 80,250,80,80,250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(m80);
      free(o250);
      free(l80);
      free(u80);
      free(crc250);
#line 1300 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_makeMatchList); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_makeMatchList)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cid, mid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 923 "fark.xs"
      int  irc;
      char *crc250;
#line 1319 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	int	mid = (int)SvIV(ST(1))
;
#line 926 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      col_makematchlist_(&cid, &mid, crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1336 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsTablePath); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsTablePath)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "oid, path");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 950 "fark.xs"
      int  irc;
      char *path250;
      char *crc250;
#line 1356 "fark.c"
	int	oid = (int)SvIV(ST(0))
;
	char *	path = (char *)SvPV_nolen(ST(1))
;
#line 954 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(path250,path);
      obs_settablepath_(&oid, path250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 1376 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearObsFileStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearObsFileStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "oid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 979 "fark.xs"
      int  irc;
      char *crc250;
#line 1395 "fark.c"
	int	oid = (int)SvIV(ST(0))
;
#line 982 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      obs_clearfilestack_(&oid,crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1410 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushObsFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushObsFile)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "oid, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1006 "fark.xs"
      int  irc;
      char *crc250;
      int i;
      char *path250;
      char* path;
      int irc2;
#line 1433 "fark.c"
	int	oid = (int)SvIV(ST(0))
;
#line 1013 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      for (i=1; i < items; i++) {
         path= (char *)SvPV_nolen(ST(i));
         strcpy(path250,path);
	 irc2=0;
         obs_pushfile_(&oid, path250, crc250, &irc2, 250, 250);
         if(irc2 != 0) {
	    irc=irc2;
	    i=items;
         }
      }
      if (irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(path250);
      free(crc250);
#line 1459 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_peekObsFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_peekObsFile)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "oid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1048 "fark.xs"
      int maxrep;
      int nrep;
      char *rep250;
      int  irc;
      char *crc250;
      int ii;
      int lenr=250;
#line 1483 "fark.c"
	int	oid = (int)SvIV(ST(0))
;
#line 1056 "fark.xs"
	irc=0;
	crc250 = calloc(sizeof(char), 251);
	obs_peekfilelen_(&oid,&maxrep,crc250,&irc,250);
        nrep=0;
        if (irc == 0) {
	  rep250 = calloc(sizeof(char), lenr*maxrep+1);
	  obs_peekfile_(&oid,&maxrep,&nrep,rep250,crc250,&irc,250,250);
	} else {
	  rep250 = calloc(sizeof(char),1);
        }
        if (irc != 0 ) {
	    EXTEND(SP, 2);
	    PUSHs(sv_2mortal(newSViv(irc)));
	    PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
	} else if (nrep > 0) {
	  EXTEND(SP, 3+nrep);
	  PUSHs(sv_2mortal(newSViv(irc)));
	  PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
	  PUSHs(sv_2mortal(newSViv(nrep)));
	  for (ii=0; ii < nrep ; ii++ ) {
	    PUSHs(sv_2mortal(newSVpv(&rep250[ii*250],250)));
	  };
	} else {
	};
	free(rep250);
        free(crc250);
#line 1513 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_popObsFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_popObsFile)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "oid, ...");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	oid = (int)SvIV(ST(0))
;
#line 1097 "fark.xs"
      int  irc;
      char *crc250;
      int i;
      char *path250;
      char* path;
      int irc2;
#line 1538 "fark.c"
#line 1104 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 251);
      path250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      for (i=1; i < items; i++) {
         path= (char *)SvPV_nolen(ST(i));
         strcpy(path250,path);
	 irc2=0;
         obs_popfile_(&oid, path250, crc250, &irc2, 250, 250);
         if(irc2 != 0) {
	    irc=irc2;
         }
      }
      if (irc == 0) {
         strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
      free(path250);
#line 1561 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsIndexLimits); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsIndexLimits)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "sid, sindex, eindex");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1137 "fark.xs"
      int  irc;
      char *s25;
      char *e25;
      char *crc250;
#line 1582 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	sindex = (char *)SvPV_nolen(ST(1))
;
	char *	eindex = (char *)SvPV_nolen(ST(2))
;
#line 1142 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      s25 = calloc(sizeof(char), 25);
      e25 = calloc(sizeof(char), 25);
      strcpy(crc250,"");
      strcpy(s25,sindex);
      strcpy(e25,eindex);
      obs_setindexlimits_(&sid,s25, e25, crc250, &irc, 25, 25, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(s25);
      free(e25);
      free(crc250);
#line 1607 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearObsTargetStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearObsTargetStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "sid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1172 "fark.xs"
      int  irc;
      char *crc250;
#line 1626 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
#line 1175 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      obs_cleartargetstack_(&sid,crc250, &irc, 250);
      if (irc == 0) {
          strcpy(crc250,"No error detected.");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1641 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushObsTarget); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushObsTarget)
{
    dVAR; dXSARGS;
    if (items != 7)
       croak_xs_usage(cv,  "sid, target, pos, descr, info, vmin, vmax");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1203 "fark.xs"
      int  irc;
      char *crc250;
#line 1660 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	target = (char *)SvPV_nolen(ST(1))
;
	char *	pos = (char *)SvPV_nolen(ST(2))
;
	char *	descr = (char *)SvPV_nolen(ST(3))
;
	char *	info = (char *)SvPV_nolen(ST(4))
;
	char *	vmin = (char *)SvPV_nolen(ST(5))
;
	char *	vmax = (char *)SvPV_nolen(ST(6))
;
#line 1206 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      obs_pushtarget_(&sid,target,pos,descr,info,vmin,vmax,crc250,&irc,strlen(target),strlen(pos),strlen(descr),strlen(info),strlen(vmin),strlen(vmax),250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1687 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsIndex); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsIndex)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "sid, target, expr");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1229 "fark.xs"
      int  irc;
      char *crc250;
      char *t80;
      char *e250;
#line 1708 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	char *	target = (char *)SvPV_nolen(ST(1))
;
	char *	expr = (char *)SvPV_nolen(ST(2))
;
#line 1234 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      t80 = calloc(sizeof(char), 80);
      e250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(t80,target);
      strcpy(e250,expr);
      obs_setindex_(&sid, t80, e250,crc250, &irc, 80,250,250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(t80);
      free(e250);
      free(crc250);
#line 1733 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsBufrType); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsBufrType)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "sid, bufrType, subType");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1264 "fark.xs"
      int  irc;
      char *crc250;
#line 1752 "fark.c"
	int	sid = (int)SvIV(ST(0))
;
	int	bufrType = (int)SvIV(ST(1))
;
	int	subType = (int)SvIV(ST(2))
;
#line 1267 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      obs_setbufrtype_(&sid, &bufrType, &subType, crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      }
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1771 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_expression); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_expression)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "exp");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1291 "fark.xs"
      char *exp250;
      int  irc;
      char *crc250;
#line 1791 "fark.c"
	char *	exp = (char *)SvPV_nolen(ST(0))
;
#line 1295 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      exp250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(exp250,exp);
      col_expression_(exp250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(exp250,strlen(exp250))));
      free(exp250);
      free(crc250);
#line 1810 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setModelFilter); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setModelFilter)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cid, filter");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1324 "fark.xs"
      int  irc;
      char *crc250;
#line 1829 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	filter = (char *)SvPV_nolen(ST(1))
;
#line 1327 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      mod_setfilter_(&cid,filter, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1846 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setObsFilter); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setObsFilter)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "cid, filter");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1349 "fark.xs"
      int  irc;
      char *crc250;
#line 1865 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	char *	filter = (char *)SvPV_nolen(ST(1))
;
#line 1352 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      obs_setfilter_(&cid,filter, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 1882 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setColocXMLFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setColocXMLFile)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pid, fn");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1374 "fark.xs"
      char *fn250;
      int  irc;
      char *crc250;
#line 1902 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	fn = (char *)SvPV_nolen(ST(1))
;
#line 1378 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      fn250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(fn250,fn);
      col_setxmlfile_(&pid, fn250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(fn250);
      free(crc250);
#line 1922 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_getColocXMLFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_getColocXMLFile)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1403 "fark.xs"
      char *fn250;
      int  irc;
      char *crc250;
#line 1942 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1407 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      fn250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(fn250,"");
      col_getxmlfile_(&pid, fn250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(fn250,strlen(fn250))));
      free(fn250);
      free(crc250);
#line 1961 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setShapeFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setShapeFile)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fn, cn");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1433 "fark.xs"
      char *fn250;
      char *cn11;
      int  irc;
      char *crc250;
#line 1982 "fark.c"
	char *	fn = (char *)SvPV_nolen(ST(0))
;
	char *	cn = (char *)SvPV_nolen(ST(1))
;
#line 1438 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      fn250 = calloc(sizeof(char), 250);
      cn11 = calloc(sizeof(char), 11);
      strcpy(crc250,"");
      strcpy(fn250,fn);
      strcpy(cn11,cn);
      par_setshapefile_(fn250, cn11, crc250, &irc, 250, 11, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(cn11);
      free(fn250);
      free(crc250);
#line 2005 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_simplifyShapes); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_simplifyShapes)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "tol");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1466 "fark.xs"
      char *tol20;
      int  irc;
      char *crc250;
#line 2025 "fark.c"
	char *	tol = (char *)SvPV_nolen(ST(0))
;
#line 1470 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      tol20 = calloc(sizeof(char), 20);
      strcpy(crc250,"");
      strcpy(tol20,tol);
      par_simplifyshapes_(tol20, crc250, &irc, 20, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(tol20);
      free(crc250);
#line 2043 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearShapeFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearShapeFile)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1494 "fark.xs"
      int  irc;
      char *crc250;
#line 2062 "fark.c"
#line 1497 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      par_clearshapefile_(crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2075 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_makeColocXML); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_makeColocXML)
{
    dVAR; dXSARGS;
    if (items != 6)
       croak_xs_usage(cv,  "cid, mid, oid, xml, test, fill");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1523 "fark.xs"
      char *xml250;
      int  irc;
      char *crc250;
      char *fill250;
#line 2096 "fark.c"
	int	cid = (int)SvIV(ST(0))
;
	int	mid = (int)SvIV(ST(1))
;
	int	oid = (int)SvIV(ST(2))
;
	char *	xml = (char *)SvPV_nolen(ST(3))
;
	int	test = (int)SvIV(ST(4))
;
	char *	fill = (char *)SvPV_nolen(ST(5))
;
#line 1528 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      fill250 = calloc(sizeof(char), 250);
      xml250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
strcpy(fill250,fill);
      strcpy(xml250,xml);
      col_makexml_(&cid, &mid, &oid, xml250, &test, fill250,crc250, &irc, 250, 250,250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(xml250,strlen(xml250))));
      free(xml250);
      free(fill250);
      free(crc250);
#line 2128 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_makePlotTable); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_makePlotTable)
{
    dVAR; dXSARGS;
    if (items != 9)
       croak_xs_usage(cv,  "pid, cid, mid, oid, table, graph, cat, test, fill");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1562 "fark.xs"
      char *tab250;
      char *gra250;
      char *cat250;
      char *fill250;
      int  irc;
      char *crc250;
#line 2151 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	int	cid = (int)SvIV(ST(1))
;
	int	mid = (int)SvIV(ST(2))
;
	int	oid = (int)SvIV(ST(3))
;
	char *	table = (char *)SvPV_nolen(ST(4))
;
	char *	graph = (char *)SvPV_nolen(ST(5))
;
	char*	cat = (char *)SvPV_nolen(ST(6))
;
	int	test = (int)SvIV(ST(7))
;
	char *	fill = (char *)SvPV_nolen(ST(8))
;
#line 1569 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      tab250 = calloc(sizeof(char), 250);
      gra250 = calloc(sizeof(char), 250);
      cat250 = calloc(sizeof(char), 250);
      fill250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(tab250,table);
      strcpy(gra250,graph);
      strcpy(cat250,cat);
      strcpy(fill250,fill);
      plo_maketable_(&pid,&cid,&mid,&oid,tab250,gra250,cat250,&test,fill250,crc250,&irc,250,250,250,250,250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 4);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(tab250,strlen(tab250))));
      PUSHs(sv_2mortal(newSVpv(gra250,strlen(gra250))));
      free(tab250);
      free(gra250);
      free(cat250);
      free(fill250);
      free(crc250);
#line 2196 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setPlotType); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setPlotType)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pid, type");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1605 "fark.xs"
      char *type250;
      int  irc;
      char *crc250;
#line 2216 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	type = (char *)SvPV_nolen(ST(1))
;
#line 1609 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      type250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(type250,type);
      plo_settype_(&pid, type250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(type250);
      free(crc250);
#line 2236 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setPlotTableFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setPlotTableFile)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pid, fn");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1634 "fark.xs"
      char *fn250;
      int  irc;
      char *crc250;
#line 2256 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	fn = (char *)SvPV_nolen(ST(1))
;
#line 1638 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      fn250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(fn250,fn);
      plo_settablefile_(&pid, fn250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(fn250);
      free(crc250);
#line 2276 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_getPlotTableFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_getPlotTableFile)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1663 "fark.xs"
      char *fn250;
      int  irc;
      char *crc250;
#line 2296 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1667 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      fn250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(fn250,"");
      plo_gettablefile_(&pid, fn250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(fn250,strlen(fn250))));
      free(fn250);
      free(crc250);
#line 2315 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setPlotGraphicsFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setPlotGraphicsFile)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pid, fn");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1693 "fark.xs"
      char *fn250;
      int  irc;
      char *crc250;
#line 2335 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	fn = (char *)SvPV_nolen(ST(1))
;
#line 1697 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      fn250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(fn250,fn);
      plo_setgraphicsfile_(&pid, fn250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(fn250);
      free(crc250);
#line 2355 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_getPlotGraphicsFile); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_getPlotGraphicsFile)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1722 "fark.xs"
      char *fn250;
      int  irc;
      char *crc250;
#line 2375 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1726 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      fn250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(fn250,"");
      plo_getgraphicsfile_(&pid, fn250, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 3);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      PUSHs(sv_2mortal(newSVpv(fn250,strlen(fn250))));
      free(fn250);
      free(crc250);
#line 2394 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_strepPlotFiles); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_strepPlotFiles)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1751 "fark.xs"
      int  irc;
      char *crc250;
#line 2413 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1754 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      plo_strepfiles_(&pid, crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2428 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearPlotAttributeStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearPlotAttributeStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1775 "fark.xs"
      int  irc;
      char *crc250;
#line 2447 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1778 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      plo_clearattrstack_(&pid, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2462 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushPlotAttribute); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushPlotAttribute)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "pid, name, value");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1802 "fark.xs"
      char *name80;
      char *value250;
      int  irc;
      char *crc250;
#line 2483 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	name = (char *)SvPV_nolen(ST(1))
;
	char *	value = (char *)SvPV_nolen(ST(2))
;
#line 1807 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      name80 = calloc(sizeof(char), 80);
      value250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(name80,name);
      strcpy(value250,value);
      plo_pushattr_(&pid, name80, value250, crc250, &irc, 80, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(name80);
      free(value250);
      free(crc250);
#line 2508 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearPlotSetStack); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearPlotSetStack)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1834 "fark.xs"
      int  irc;
      char *crc250;
#line 2527 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1837 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      plo_clearsetstack_(&pid, crc250, &irc, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2542 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_clearPlotColumn); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_clearPlotColumn)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pid");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1860 "fark.xs"
      int  irc;
      char *crc250;
#line 2561 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
#line 1863 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      plo_clearcolumn_(&pid, crc250, &irc, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(crc250);
#line 2576 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushPlotColumn); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushPlotColumn)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "pid, name, expr");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1888 "fark.xs"
      char *name80;
      char *exp250;
      int  irc;
      char *crc250;
#line 2597 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	char *	name = (char *)SvPV_nolen(ST(1))
;
	char *	expr = (char *)SvPV_nolen(ST(2))
;
#line 1893 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      name80 = calloc(sizeof(char), 80);
      exp250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(name80,name);
      strcpy(exp250,expr);
      plo_pushcolumn_(&pid, name80, exp250, crc250, &irc, 80, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(name80);
      free(exp250);
      free(crc250);
#line 2622 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_pushPlotSet); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_pushPlotSet)
{
    dVAR; dXSARGS;
    if (items != 6)
       croak_xs_usage(cv,  "pid, cid, mid, oid, name, legend");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 1929 "fark.xs"
      char *name80;
      char *legend250;
      int  irc;
      char *crc250;
#line 2643 "fark.c"
	int	pid = (int)SvIV(ST(0))
;
	int	cid = (int)SvIV(ST(1))
;
	int	mid = (int)SvIV(ST(2))
;
	int	oid = (int)SvIV(ST(3))
;
	char *	name = (char *)SvPV_nolen(ST(4))
;
	char *	legend = (char *)SvPV_nolen(ST(5))
;
#line 1934 "fark.xs"
      irc=0;
      crc250 = calloc(sizeof(char), 250);
      name80 = calloc(sizeof(char), 80);
      legend250 = calloc(sizeof(char), 250);
      strcpy(crc250,"");
      strcpy(name80,name);
      strcpy(legend250,legend);
      plo_pushset_(&pid, &cid, &mid, &oid, name80, legend250, crc250, &irc, 80, 250, 250);
      if(irc == 0) {
         strcpy(crc250,"");
      };
      EXTEND(SP, 2);
      PUSHs(sv_2mortal(newSViv(irc)));
      PUSHs(sv_2mortal(newSVpv(crc250,strlen(crc250))));
      free(name80);
      free(legend250);
      free(crc250);
#line 2674 "fark.c"
	PUTBACK;
	return;
    }
}


XS_EUPXS(XS_fark_xs_setDebug); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_fark_xs_setDebug)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "ideb");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	int	ideb = (int)SvIV(ST(0))
;
#line 1958 "fark.xs"
      plo_setdebug_(&ideb);
#line 2694 "fark.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_fark); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_fark)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("fark::xs_openModelSession", XS_fark_xs_openModelSession);
        newXS_deffile("fark::xs_closeModelSession", XS_fark_xs_closeModelSession);
        newXS_deffile("fark::xs_openObsSession", XS_fark_xs_openObsSession);
        newXS_deffile("fark::xs_closeObsSession", XS_fark_xs_closeObsSession);
        newXS_deffile("fark::xs_openColocSession", XS_fark_xs_openColocSession);
        newXS_deffile("fark::xs_closeColocSession", XS_fark_xs_closeColocSession);
        newXS_deffile("fark::xs_openPlotSession", XS_fark_xs_openPlotSession);
        newXS_deffile("fark::xs_closePlotSession", XS_fark_xs_closePlotSession);
        newXS_deffile("fark::xs_makeModelCache", XS_fark_xs_makeModelCache);
        newXS_deffile("fark::xs_makeObsCache", XS_fark_xs_makeObsCache);
        newXS_deffile("fark::xs_loadModelCache", XS_fark_xs_loadModelCache);
        newXS_deffile("fark::xs_setModelCache", XS_fark_xs_setModelCache);
        newXS_deffile("fark::xs_loadObsCache", XS_fark_xs_loadObsCache);
        newXS_deffile("fark::xs_setObsCache", XS_fark_xs_setObsCache);
        newXS_deffile("fark::xs_clearModelFileStack", XS_fark_xs_clearModelFileStack);
        newXS_deffile("fark::xs_clearModelTargetStack", XS_fark_xs_clearModelTargetStack);
        newXS_deffile("fark::xs_clearDefaultStack", XS_fark_xs_clearDefaultStack);
        newXS_deffile("fark::xs_pushModelFile", XS_fark_xs_pushModelFile);
        newXS_deffile("fark::xs_peekModelFile", XS_fark_xs_peekModelFile);
        newXS_deffile("fark::xs_popModelFile", XS_fark_xs_popModelFile);
        newXS_deffile("fark::xs_setModelIndex", XS_fark_xs_setModelIndex);
        newXS_deffile("fark::xs_setModelIndexLimits", XS_fark_xs_setModelIndexLimits);
        newXS_deffile("fark::xs_pushModelTarget", XS_fark_xs_pushModelTarget);
        newXS_deffile("fark::xs_addDefault", XS_fark_xs_addDefault);
        newXS_deffile("fark::xs_pushDefault", XS_fark_xs_pushDefault);
        newXS_deffile("fark::xs_clearMatchRuleStack", XS_fark_xs_clearMatchRuleStack);
        newXS_deffile("fark::xs_pushMatchRule", XS_fark_xs_pushMatchRule);
        newXS_deffile("fark::xs_makeMatchList", XS_fark_xs_makeMatchList);
        newXS_deffile("fark::xs_setObsTablePath", XS_fark_xs_setObsTablePath);
        newXS_deffile("fark::xs_clearObsFileStack", XS_fark_xs_clearObsFileStack);
        newXS_deffile("fark::xs_pushObsFile", XS_fark_xs_pushObsFile);
        newXS_deffile("fark::xs_peekObsFile", XS_fark_xs_peekObsFile);
        newXS_deffile("fark::xs_popObsFile", XS_fark_xs_popObsFile);
        newXS_deffile("fark::xs_setObsIndexLimits", XS_fark_xs_setObsIndexLimits);
        newXS_deffile("fark::xs_clearObsTargetStack", XS_fark_xs_clearObsTargetStack);
        newXS_deffile("fark::xs_pushObsTarget", XS_fark_xs_pushObsTarget);
        newXS_deffile("fark::xs_setObsIndex", XS_fark_xs_setObsIndex);
        newXS_deffile("fark::xs_setObsBufrType", XS_fark_xs_setObsBufrType);
        newXS_deffile("fark::xs_expression", XS_fark_xs_expression);
        newXS_deffile("fark::xs_setModelFilter", XS_fark_xs_setModelFilter);
        newXS_deffile("fark::xs_setObsFilter", XS_fark_xs_setObsFilter);
        newXS_deffile("fark::xs_setColocXMLFile", XS_fark_xs_setColocXMLFile);
        newXS_deffile("fark::xs_getColocXMLFile", XS_fark_xs_getColocXMLFile);
        newXS_deffile("fark::xs_setShapeFile", XS_fark_xs_setShapeFile);
        newXS_deffile("fark::xs_simplifyShapes", XS_fark_xs_simplifyShapes);
        newXS_deffile("fark::xs_clearShapeFile", XS_fark_xs_clearShapeFile);
        newXS_deffile("fark::xs_makeColocXML", XS_fark_xs_makeColocXML);
        newXS_deffile("fark::xs_makePlotTable", XS_fark_xs_makePlotTable);
        newXS_deffile("fark::xs_setPlotType", XS_fark_xs_setPlotType);
        newXS_deffile("fark::xs_setPlotTableFile", XS_fark_xs_setPlotTableFile);
        newXS_deffile("fark::xs_getPlotTableFile", XS_fark_xs_getPlotTableFile);
        newXS_deffile("fark::xs_setPlotGraphicsFile", XS_fark_xs_setPlotGraphicsFile);
        newXS_deffile("fark::xs_getPlotGraphicsFile", XS_fark_xs_getPlotGraphicsFile);
        newXS_deffile("fark::xs_strepPlotFiles", XS_fark_xs_strepPlotFiles);
        newXS_deffile("fark::xs_clearPlotAttributeStack", XS_fark_xs_clearPlotAttributeStack);
        newXS_deffile("fark::xs_pushPlotAttribute", XS_fark_xs_pushPlotAttribute);
        newXS_deffile("fark::xs_clearPlotSetStack", XS_fark_xs_clearPlotSetStack);
        newXS_deffile("fark::xs_clearPlotColumn", XS_fark_xs_clearPlotColumn);
        newXS_deffile("fark::xs_pushPlotColumn", XS_fark_xs_pushPlotColumn);
        newXS_deffile("fark::xs_pushPlotSet", XS_fark_xs_pushPlotSet);
        newXS_deffile("fark::xs_setDebug", XS_fark_xs_setDebug);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

