#! /bin/csh
#
rm -f output/*/*;
R CMD build farkRPackage &&sudo R -e 'install.packages("farkRPackage_0.2.0.tar.gz", repos=NULL)' && Rscript --vanilla splus/synop test.table output/test/
#
  eog output/*/*.jpg
#
# gthumb output/*/*.ps
#
